linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  enable-all: false
run:
  timeout: 20m
issues:
  exclude-files:
    - schema.go
    - pulumiManifest.go
