version: "2"
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - schema.go
      - pulumiManifest.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - schema.go
      - pulumiManifest.go
      - third_party$
      - builtin$
      - examples$
