version: 2
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-datarobot
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ignore: []
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/datarobot-community/pulumi-datarobot/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-datarobot/
changelog:
  filters:
    exclude:
    - Merge branch
    - Merge pull request
    - \Winternal\W
    - \Wci\W
    - \Wchore\W
  sort: asc
  use: git
release:
  disable: false
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
project_name: "pulumi-datarobot"
