// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datarobot
{
    [DatarobotResourceType("datarobot:index/apiTokenCredential:ApiTokenCredential")]
    public partial class ApiTokenCredential : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        [Output("apiToken")]
        public Output<string> ApiToken { get; private set; } = null!;

        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The name of the Api Token Credential.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a ApiTokenCredential resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApiTokenCredential(string name, ApiTokenCredentialArgs args, CustomResourceOptions? options = null)
            : base("datarobot:index/apiTokenCredential:ApiTokenCredential", name, args ?? new ApiTokenCredentialArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApiTokenCredential(string name, Input<string> id, ApiTokenCredentialState? state = null, CustomResourceOptions? options = null)
            : base("datarobot:index/apiTokenCredential:ApiTokenCredential", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "apiToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApiTokenCredential resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApiTokenCredential Get(string name, Input<string> id, ApiTokenCredentialState? state = null, CustomResourceOptions? options = null)
        {
            return new ApiTokenCredential(name, id, state, options);
        }
    }

    public sealed class ApiTokenCredentialArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiToken", required: true)]
        private Input<string>? _apiToken;

        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        public Input<string>? ApiToken
        {
            get => _apiToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// The name of the Api Token Credential.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ApiTokenCredentialArgs()
        {
        }
        public static new ApiTokenCredentialArgs Empty => new ApiTokenCredentialArgs();
    }

    public sealed class ApiTokenCredentialState : global::Pulumi.ResourceArgs
    {
        [Input("apiToken")]
        private Input<string>? _apiToken;

        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        public Input<string>? ApiToken
        {
            get => _apiToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The description of the Api Token Credential.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the Api Token Credential.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ApiTokenCredentialState()
        {
        }
        public static new ApiTokenCredentialState Empty => new ApiTokenCredentialState();
    }
}
