// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datarobot
{
    [DatarobotResourceType("datarobot:index/datasetFromFile:DatasetFromFile")]
    public partial class DatasetFromFile : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the Dataset.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The path to the file to upload.
        /// </summary>
        [Output("sourceFile")]
        public Output<string> SourceFile { get; private set; } = null!;

        /// <summary>
        /// The id of the Use Case.
        /// </summary>
        [Output("useCaseId")]
        public Output<string> UseCaseId { get; private set; } = null!;


        /// <summary>
        /// Create a DatasetFromFile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DatasetFromFile(string name, DatasetFromFileArgs args, CustomResourceOptions? options = null)
            : base("datarobot:index/datasetFromFile:DatasetFromFile", name, args ?? new DatasetFromFileArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DatasetFromFile(string name, Input<string> id, DatasetFromFileState? state = null, CustomResourceOptions? options = null)
            : base("datarobot:index/datasetFromFile:DatasetFromFile", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DatasetFromFile resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DatasetFromFile Get(string name, Input<string> id, DatasetFromFileState? state = null, CustomResourceOptions? options = null)
        {
            return new DatasetFromFile(name, id, state, options);
        }
    }

    public sealed class DatasetFromFileArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Dataset.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the file to upload.
        /// </summary>
        [Input("sourceFile", required: true)]
        public Input<string> SourceFile { get; set; } = null!;

        /// <summary>
        /// The id of the Use Case.
        /// </summary>
        [Input("useCaseId", required: true)]
        public Input<string> UseCaseId { get; set; } = null!;

        public DatasetFromFileArgs()
        {
        }
        public static new DatasetFromFileArgs Empty => new DatasetFromFileArgs();
    }

    public sealed class DatasetFromFileState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Dataset.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the file to upload.
        /// </summary>
        [Input("sourceFile")]
        public Input<string>? SourceFile { get; set; }

        /// <summary>
        /// The id of the Use Case.
        /// </summary>
        [Input("useCaseId")]
        public Input<string>? UseCaseId { get; set; }

        public DatasetFromFileState()
        {
        }
        public static new DatasetFromFileState Empty => new DatasetFromFileState();
    }
}
