// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot
{
    public static class GetGlobalModel
    {
        /// <summary>
        /// Global Model
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as datarobot from "@datarobot/pulumi-datarobot";
        /// 
        /// const dummyBinaryClassification = datarobot.getGlobalModel({
        ///     name: "[DataRobot] Dummy Binary Classification",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_datarobot as datarobot
        /// 
        /// dummy_binary_classification = datarobot.get_global_model(name="[DataRobot] Dummy Binary Classification")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datarobot = DataRobotPulumi.Datarobot;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dummyBinaryClassification = Datarobot.GetGlobalModel.Invoke(new()
        ///     {
        ///         Name = "[DataRobot] Dummy Binary Classification",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := datarobot.GetGlobalModel(ctx, &amp;datarobot.GetGlobalModelArgs{
        /// 			Name: "[DataRobot] Dummy Binary Classification",
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     datarobot = {
        ///       source = "pulumi/datarobot"
        ///     }
        ///   }
        /// }
        /// 
        /// data "datarobot_getglobalmodel" "dummyBinaryClassification" {
        ///   name = "[DataRobot] Dummy Binary Classification"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.datarobot.DatarobotFunctions;
        /// import com.pulumi.datarobot.inputs.GetGlobalModelArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var dummyBinaryClassification = DatarobotFunctions.getGlobalModel(GetGlobalModelArgs.builder()
        ///             .name("[DataRobot] Dummy Binary Classification")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   dummyBinaryClassification:
        ///     fn::invoke:
        ///       function: datarobot:getGlobalModel
        ///       arguments:
        ///         name: '[DataRobot] Dummy Binary Classification'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetGlobalModelResult> InvokeAsync(GetGlobalModelArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGlobalModelResult>("datarobot:index/getGlobalModel:getGlobalModel", args ?? new GetGlobalModelArgs(), options.WithDefaults());

        /// <summary>
        /// Global Model
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as datarobot from "@datarobot/pulumi-datarobot";
        /// 
        /// const dummyBinaryClassification = datarobot.getGlobalModel({
        ///     name: "[DataRobot] Dummy Binary Classification",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_datarobot as datarobot
        /// 
        /// dummy_binary_classification = datarobot.get_global_model(name="[DataRobot] Dummy Binary Classification")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datarobot = DataRobotPulumi.Datarobot;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dummyBinaryClassification = Datarobot.GetGlobalModel.Invoke(new()
        ///     {
        ///         Name = "[DataRobot] Dummy Binary Classification",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := datarobot.GetGlobalModel(ctx, &amp;datarobot.GetGlobalModelArgs{
        /// 			Name: "[DataRobot] Dummy Binary Classification",
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     datarobot = {
        ///       source = "pulumi/datarobot"
        ///     }
        ///   }
        /// }
        /// 
        /// data "datarobot_getglobalmodel" "dummyBinaryClassification" {
        ///   name = "[DataRobot] Dummy Binary Classification"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.datarobot.DatarobotFunctions;
        /// import com.pulumi.datarobot.inputs.GetGlobalModelArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var dummyBinaryClassification = DatarobotFunctions.getGlobalModel(GetGlobalModelArgs.builder()
        ///             .name("[DataRobot] Dummy Binary Classification")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   dummyBinaryClassification:
        ///     fn::invoke:
        ///       function: datarobot:getGlobalModel
        ///       arguments:
        ///         name: '[DataRobot] Dummy Binary Classification'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetGlobalModelResult> Invoke(GetGlobalModelInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGlobalModelResult>("datarobot:index/getGlobalModel:getGlobalModel", args ?? new GetGlobalModelInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Global Model
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as datarobot from "@datarobot/pulumi-datarobot";
        /// 
        /// const dummyBinaryClassification = datarobot.getGlobalModel({
        ///     name: "[DataRobot] Dummy Binary Classification",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_datarobot as datarobot
        /// 
        /// dummy_binary_classification = datarobot.get_global_model(name="[DataRobot] Dummy Binary Classification")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datarobot = DataRobotPulumi.Datarobot;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dummyBinaryClassification = Datarobot.GetGlobalModel.Invoke(new()
        ///     {
        ///         Name = "[DataRobot] Dummy Binary Classification",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := datarobot.GetGlobalModel(ctx, &amp;datarobot.GetGlobalModelArgs{
        /// 			Name: "[DataRobot] Dummy Binary Classification",
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     datarobot = {
        ///       source = "pulumi/datarobot"
        ///     }
        ///   }
        /// }
        /// 
        /// data "datarobot_getglobalmodel" "dummyBinaryClassification" {
        ///   name = "[DataRobot] Dummy Binary Classification"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.datarobot.DatarobotFunctions;
        /// import com.pulumi.datarobot.inputs.GetGlobalModelArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var dummyBinaryClassification = DatarobotFunctions.getGlobalModel(GetGlobalModelArgs.builder()
        ///             .name("[DataRobot] Dummy Binary Classification")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   dummyBinaryClassification:
        ///     fn::invoke:
        ///       function: datarobot:getGlobalModel
        ///       arguments:
        ///         name: '[DataRobot] Dummy Binary Classification'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetGlobalModelResult> Invoke(GetGlobalModelInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetGlobalModelResult>("datarobot:index/getGlobalModel:getGlobalModel", args ?? new GetGlobalModelInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGlobalModelArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Registered Model.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetGlobalModelArgs()
        {
        }
        public static new GetGlobalModelArgs Empty => new GetGlobalModelArgs();
    }

    public sealed class GetGlobalModelInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Registered Model.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetGlobalModelInvokeArgs()
        {
        }
        public static new GetGlobalModelInvokeArgs Empty => new GetGlobalModelInvokeArgs();
    }


    [OutputType]
    public sealed class GetGlobalModelResult
    {
        /// <summary>
        /// The ID of the Global Model.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the Registered Model.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the Global Model Version.
        /// </summary>
        public readonly string VersionId;

        [OutputConstructor]
        private GetGlobalModelResult(
            string id,

            string name,

            string versionId)
        {
            Id = id;
            Name = name;
            VersionId = versionId;
        }
    }
}
