// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datarobot

import (
	"context"
	"reflect"

	"errors"
	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A custom model packaged from a vector database (the vector database "send to custom model workshop" operation). Changing the source vector database or any compute setting forces a new custom model to be created.
type CustomModelFromVectorDatabase struct {
	pulumi.CustomResourceState

	// The description of the Custom Model.
	Description pulumi.StringOutput `pulumi:"description"`
	// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
	MemoryMb pulumi.IntOutput `pulumi:"memoryMb"`
	// The name of the Custom Model.
	Name pulumi.StringOutput `pulumi:"name"`
	// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
	NetworkEgressPolicy pulumi.StringOutput `pulumi:"networkEgressPolicy"`
	// The number of replicas to deploy for the Custom Model.
	Replicas pulumi.IntOutput `pulumi:"replicas"`
	// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
	ResourceBundleId pulumi.StringOutput `pulumi:"resourceBundleId"`
	// The ID of the source Vector Database for the Custom Model.
	VectorDatabaseId pulumi.StringOutput `pulumi:"vectorDatabaseId"`
	// The ID of the latest Custom Model version.
	VersionId pulumi.StringOutput `pulumi:"versionId"`
}

// NewCustomModelFromVectorDatabase registers a new resource with the given unique name, arguments, and options.
func NewCustomModelFromVectorDatabase(ctx *pulumi.Context,
	name string, args *CustomModelFromVectorDatabaseArgs, opts ...pulumi.ResourceOption) (*CustomModelFromVectorDatabase, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.VectorDatabaseId == nil {
		return nil, errors.New("invalid value for required argument 'VectorDatabaseId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CustomModelFromVectorDatabase
	err := ctx.RegisterResource("datarobot:index/customModelFromVectorDatabase:CustomModelFromVectorDatabase", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCustomModelFromVectorDatabase gets an existing CustomModelFromVectorDatabase resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCustomModelFromVectorDatabase(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CustomModelFromVectorDatabaseState, opts ...pulumi.ResourceOption) (*CustomModelFromVectorDatabase, error) {
	var resource CustomModelFromVectorDatabase
	err := ctx.ReadResource("datarobot:index/customModelFromVectorDatabase:CustomModelFromVectorDatabase", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CustomModelFromVectorDatabase resources.
type customModelFromVectorDatabaseState struct {
	// The description of the Custom Model.
	Description *string `pulumi:"description"`
	// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
	MemoryMb *int `pulumi:"memoryMb"`
	// The name of the Custom Model.
	Name *string `pulumi:"name"`
	// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
	NetworkEgressPolicy *string `pulumi:"networkEgressPolicy"`
	// The number of replicas to deploy for the Custom Model.
	Replicas *int `pulumi:"replicas"`
	// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
	ResourceBundleId *string `pulumi:"resourceBundleId"`
	// The ID of the source Vector Database for the Custom Model.
	VectorDatabaseId *string `pulumi:"vectorDatabaseId"`
	// The ID of the latest Custom Model version.
	VersionId *string `pulumi:"versionId"`
}

type CustomModelFromVectorDatabaseState struct {
	// The description of the Custom Model.
	Description pulumi.StringPtrInput
	// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
	MemoryMb pulumi.IntPtrInput
	// The name of the Custom Model.
	Name pulumi.StringPtrInput
	// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
	NetworkEgressPolicy pulumi.StringPtrInput
	// The number of replicas to deploy for the Custom Model.
	Replicas pulumi.IntPtrInput
	// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
	ResourceBundleId pulumi.StringPtrInput
	// The ID of the source Vector Database for the Custom Model.
	VectorDatabaseId pulumi.StringPtrInput
	// The ID of the latest Custom Model version.
	VersionId pulumi.StringPtrInput
}

func (CustomModelFromVectorDatabaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*customModelFromVectorDatabaseState)(nil)).Elem()
}

type customModelFromVectorDatabaseArgs struct {
	// The description of the Custom Model.
	Description *string `pulumi:"description"`
	// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
	MemoryMb *int `pulumi:"memoryMb"`
	// The name of the Custom Model.
	Name *string `pulumi:"name"`
	// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
	NetworkEgressPolicy *string `pulumi:"networkEgressPolicy"`
	// The number of replicas to deploy for the Custom Model.
	Replicas *int `pulumi:"replicas"`
	// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
	ResourceBundleId *string `pulumi:"resourceBundleId"`
	// The ID of the source Vector Database for the Custom Model.
	VectorDatabaseId string `pulumi:"vectorDatabaseId"`
}

// The set of arguments for constructing a CustomModelFromVectorDatabase resource.
type CustomModelFromVectorDatabaseArgs struct {
	// The description of the Custom Model.
	Description pulumi.StringPtrInput
	// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
	MemoryMb pulumi.IntPtrInput
	// The name of the Custom Model.
	Name pulumi.StringPtrInput
	// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
	NetworkEgressPolicy pulumi.StringPtrInput
	// The number of replicas to deploy for the Custom Model.
	Replicas pulumi.IntPtrInput
	// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
	ResourceBundleId pulumi.StringPtrInput
	// The ID of the source Vector Database for the Custom Model.
	VectorDatabaseId pulumi.StringInput
}

func (CustomModelFromVectorDatabaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*customModelFromVectorDatabaseArgs)(nil)).Elem()
}

type CustomModelFromVectorDatabaseInput interface {
	pulumi.Input

	ToCustomModelFromVectorDatabaseOutput() CustomModelFromVectorDatabaseOutput
	ToCustomModelFromVectorDatabaseOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseOutput
}

func (*CustomModelFromVectorDatabase) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomModelFromVectorDatabase)(nil)).Elem()
}

func (i *CustomModelFromVectorDatabase) ToCustomModelFromVectorDatabaseOutput() CustomModelFromVectorDatabaseOutput {
	return i.ToCustomModelFromVectorDatabaseOutputWithContext(context.Background())
}

func (i *CustomModelFromVectorDatabase) ToCustomModelFromVectorDatabaseOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomModelFromVectorDatabaseOutput)
}

// CustomModelFromVectorDatabaseArrayInput is an input type that accepts CustomModelFromVectorDatabaseArray and CustomModelFromVectorDatabaseArrayOutput values.
// You can construct a concrete instance of `CustomModelFromVectorDatabaseArrayInput` via:
//
//	CustomModelFromVectorDatabaseArray{ CustomModelFromVectorDatabaseArgs{...} }
type CustomModelFromVectorDatabaseArrayInput interface {
	pulumi.Input

	ToCustomModelFromVectorDatabaseArrayOutput() CustomModelFromVectorDatabaseArrayOutput
	ToCustomModelFromVectorDatabaseArrayOutputWithContext(context.Context) CustomModelFromVectorDatabaseArrayOutput
}

type CustomModelFromVectorDatabaseArray []CustomModelFromVectorDatabaseInput

func (CustomModelFromVectorDatabaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomModelFromVectorDatabase)(nil)).Elem()
}

func (i CustomModelFromVectorDatabaseArray) ToCustomModelFromVectorDatabaseArrayOutput() CustomModelFromVectorDatabaseArrayOutput {
	return i.ToCustomModelFromVectorDatabaseArrayOutputWithContext(context.Background())
}

func (i CustomModelFromVectorDatabaseArray) ToCustomModelFromVectorDatabaseArrayOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomModelFromVectorDatabaseArrayOutput)
}

// CustomModelFromVectorDatabaseMapInput is an input type that accepts CustomModelFromVectorDatabaseMap and CustomModelFromVectorDatabaseMapOutput values.
// You can construct a concrete instance of `CustomModelFromVectorDatabaseMapInput` via:
//
//	CustomModelFromVectorDatabaseMap{ "key": CustomModelFromVectorDatabaseArgs{...} }
type CustomModelFromVectorDatabaseMapInput interface {
	pulumi.Input

	ToCustomModelFromVectorDatabaseMapOutput() CustomModelFromVectorDatabaseMapOutput
	ToCustomModelFromVectorDatabaseMapOutputWithContext(context.Context) CustomModelFromVectorDatabaseMapOutput
}

type CustomModelFromVectorDatabaseMap map[string]CustomModelFromVectorDatabaseInput

func (CustomModelFromVectorDatabaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomModelFromVectorDatabase)(nil)).Elem()
}

func (i CustomModelFromVectorDatabaseMap) ToCustomModelFromVectorDatabaseMapOutput() CustomModelFromVectorDatabaseMapOutput {
	return i.ToCustomModelFromVectorDatabaseMapOutputWithContext(context.Background())
}

func (i CustomModelFromVectorDatabaseMap) ToCustomModelFromVectorDatabaseMapOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomModelFromVectorDatabaseMapOutput)
}

type CustomModelFromVectorDatabaseOutput struct{ *pulumi.OutputState }

func (CustomModelFromVectorDatabaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomModelFromVectorDatabase)(nil)).Elem()
}

func (o CustomModelFromVectorDatabaseOutput) ToCustomModelFromVectorDatabaseOutput() CustomModelFromVectorDatabaseOutput {
	return o
}

func (o CustomModelFromVectorDatabaseOutput) ToCustomModelFromVectorDatabaseOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseOutput {
	return o
}

// The description of the Custom Model.
func (o CustomModelFromVectorDatabaseOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// The maximum memory in MB that may be allocated to the Custom Model. Cannot be used together with resource*bundle*id.
func (o CustomModelFromVectorDatabaseOutput) MemoryMb() pulumi.IntOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.IntOutput { return v.MemoryMb }).(pulumi.IntOutput)
}

// The name of the Custom Model.
func (o CustomModelFromVectorDatabaseOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The network access policy of the Custom Model (e.g. PUBLIC or NONE).
func (o CustomModelFromVectorDatabaseOutput) NetworkEgressPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.NetworkEgressPolicy }).(pulumi.StringOutput)
}

// The number of replicas to deploy for the Custom Model.
func (o CustomModelFromVectorDatabaseOutput) Replicas() pulumi.IntOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.IntOutput { return v.Replicas }).(pulumi.IntOutput)
}

// A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc. Cannot be used together with memory_mb.
func (o CustomModelFromVectorDatabaseOutput) ResourceBundleId() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.ResourceBundleId }).(pulumi.StringOutput)
}

// The ID of the source Vector Database for the Custom Model.
func (o CustomModelFromVectorDatabaseOutput) VectorDatabaseId() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.VectorDatabaseId }).(pulumi.StringOutput)
}

// The ID of the latest Custom Model version.
func (o CustomModelFromVectorDatabaseOutput) VersionId() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomModelFromVectorDatabase) pulumi.StringOutput { return v.VersionId }).(pulumi.StringOutput)
}

type CustomModelFromVectorDatabaseArrayOutput struct{ *pulumi.OutputState }

func (CustomModelFromVectorDatabaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomModelFromVectorDatabase)(nil)).Elem()
}

func (o CustomModelFromVectorDatabaseArrayOutput) ToCustomModelFromVectorDatabaseArrayOutput() CustomModelFromVectorDatabaseArrayOutput {
	return o
}

func (o CustomModelFromVectorDatabaseArrayOutput) ToCustomModelFromVectorDatabaseArrayOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseArrayOutput {
	return o
}

func (o CustomModelFromVectorDatabaseArrayOutput) Index(i pulumi.IntInput) CustomModelFromVectorDatabaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CustomModelFromVectorDatabase {
		return vs[0].([]*CustomModelFromVectorDatabase)[vs[1].(int)]
	}).(CustomModelFromVectorDatabaseOutput)
}

type CustomModelFromVectorDatabaseMapOutput struct{ *pulumi.OutputState }

func (CustomModelFromVectorDatabaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomModelFromVectorDatabase)(nil)).Elem()
}

func (o CustomModelFromVectorDatabaseMapOutput) ToCustomModelFromVectorDatabaseMapOutput() CustomModelFromVectorDatabaseMapOutput {
	return o
}

func (o CustomModelFromVectorDatabaseMapOutput) ToCustomModelFromVectorDatabaseMapOutputWithContext(ctx context.Context) CustomModelFromVectorDatabaseMapOutput {
	return o
}

func (o CustomModelFromVectorDatabaseMapOutput) MapIndex(k pulumi.StringInput) CustomModelFromVectorDatabaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CustomModelFromVectorDatabase {
		return vs[0].(map[string]*CustomModelFromVectorDatabase)[vs[1].(string)]
	}).(CustomModelFromVectorDatabaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomModelFromVectorDatabaseInput)(nil)).Elem(), &CustomModelFromVectorDatabase{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomModelFromVectorDatabaseArrayInput)(nil)).Elem(), CustomModelFromVectorDatabaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomModelFromVectorDatabaseMapInput)(nil)).Elem(), CustomModelFromVectorDatabaseMap{})
	pulumi.RegisterOutputType(CustomModelFromVectorDatabaseOutput{})
	pulumi.RegisterOutputType(CustomModelFromVectorDatabaseArrayOutput{})
	pulumi.RegisterOutputType(CustomModelFromVectorDatabaseMapOutput{})
}
