// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datarobot

import (
	"context"
	"reflect"

	"errors"
	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// prediction environment
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/datarobot-community/pulumi-datarobot/sdk/go/datarobot"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := datarobot.NewPredictionEnvironment(ctx, "example", &datarobot.PredictionEnvironmentArgs{
//				BatchJobsMaxConcurrent: pulumi.Int(20),
//				BatchJobsPriority:      pulumi.String("high"),
//				CredentialId:           pulumi.String("<credential_id>"),
//				DatastoreId:            pulumi.String("<datastore_id>"),
//				Description:            pulumi.String("Description for the example prediction environment"),
//				ManagedBy:              pulumi.String("selfManaged"),
//				Platform:               pulumi.String("datarobotServerless"),
//				SupportedModelFormats: pulumi.StringArray{
//					pulumi.String("datarobot"),
//					pulumi.String("customModel"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type PredictionEnvironment struct {
	pulumi.CustomResourceState

	// The maximum number of concurrent batch prediction jobs.
	BatchJobsMaxConcurrent pulumi.IntPtrOutput `pulumi:"batchJobsMaxConcurrent"`
	// The importance of batch jobs.
	BatchJobsPriority pulumi.StringPtrOutput `pulumi:"batchJobsPriority"`
	// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
	CredentialId pulumi.StringPtrOutput `pulumi:"credentialId"`
	// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
	DatastoreId pulumi.StringPtrOutput `pulumi:"datastoreId"`
	// The description of the Prediction Environment.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
	ManagedBy pulumi.StringOutput `pulumi:"managedBy"`
	// The name of the Prediction Environment.
	Name pulumi.StringOutput `pulumi:"name"`
	// The platform for the Prediction Environment.
	Platform pulumi.StringOutput `pulumi:"platform"`
	// The list of supported model formats.
	SupportedModelFormats pulumi.StringArrayOutput `pulumi:"supportedModelFormats"`
}

// NewPredictionEnvironment registers a new resource with the given unique name, arguments, and options.
func NewPredictionEnvironment(ctx *pulumi.Context,
	name string, args *PredictionEnvironmentArgs, opts ...pulumi.ResourceOption) (*PredictionEnvironment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Platform == nil {
		return nil, errors.New("invalid value for required argument 'Platform'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PredictionEnvironment
	err := ctx.RegisterResource("datarobot:index/predictionEnvironment:PredictionEnvironment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPredictionEnvironment gets an existing PredictionEnvironment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPredictionEnvironment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PredictionEnvironmentState, opts ...pulumi.ResourceOption) (*PredictionEnvironment, error) {
	var resource PredictionEnvironment
	err := ctx.ReadResource("datarobot:index/predictionEnvironment:PredictionEnvironment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PredictionEnvironment resources.
type predictionEnvironmentState struct {
	// The maximum number of concurrent batch prediction jobs.
	BatchJobsMaxConcurrent *int `pulumi:"batchJobsMaxConcurrent"`
	// The importance of batch jobs.
	BatchJobsPriority *string `pulumi:"batchJobsPriority"`
	// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
	CredentialId *string `pulumi:"credentialId"`
	// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
	DatastoreId *string `pulumi:"datastoreId"`
	// The description of the Prediction Environment.
	Description *string `pulumi:"description"`
	// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
	ManagedBy *string `pulumi:"managedBy"`
	// The name of the Prediction Environment.
	Name *string `pulumi:"name"`
	// The platform for the Prediction Environment.
	Platform *string `pulumi:"platform"`
	// The list of supported model formats.
	SupportedModelFormats []string `pulumi:"supportedModelFormats"`
}

type PredictionEnvironmentState struct {
	// The maximum number of concurrent batch prediction jobs.
	BatchJobsMaxConcurrent pulumi.IntPtrInput
	// The importance of batch jobs.
	BatchJobsPriority pulumi.StringPtrInput
	// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
	CredentialId pulumi.StringPtrInput
	// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
	DatastoreId pulumi.StringPtrInput
	// The description of the Prediction Environment.
	Description pulumi.StringPtrInput
	// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
	ManagedBy pulumi.StringPtrInput
	// The name of the Prediction Environment.
	Name pulumi.StringPtrInput
	// The platform for the Prediction Environment.
	Platform pulumi.StringPtrInput
	// The list of supported model formats.
	SupportedModelFormats pulumi.StringArrayInput
}

func (PredictionEnvironmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*predictionEnvironmentState)(nil)).Elem()
}

type predictionEnvironmentArgs struct {
	// The maximum number of concurrent batch prediction jobs.
	BatchJobsMaxConcurrent *int `pulumi:"batchJobsMaxConcurrent"`
	// The importance of batch jobs.
	BatchJobsPriority *string `pulumi:"batchJobsPriority"`
	// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
	CredentialId *string `pulumi:"credentialId"`
	// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
	DatastoreId *string `pulumi:"datastoreId"`
	// The description of the Prediction Environment.
	Description *string `pulumi:"description"`
	// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
	ManagedBy *string `pulumi:"managedBy"`
	// The name of the Prediction Environment.
	Name *string `pulumi:"name"`
	// The platform for the Prediction Environment.
	Platform string `pulumi:"platform"`
	// The list of supported model formats.
	SupportedModelFormats []string `pulumi:"supportedModelFormats"`
}

// The set of arguments for constructing a PredictionEnvironment resource.
type PredictionEnvironmentArgs struct {
	// The maximum number of concurrent batch prediction jobs.
	BatchJobsMaxConcurrent pulumi.IntPtrInput
	// The importance of batch jobs.
	BatchJobsPriority pulumi.StringPtrInput
	// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
	CredentialId pulumi.StringPtrInput
	// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
	DatastoreId pulumi.StringPtrInput
	// The description of the Prediction Environment.
	Description pulumi.StringPtrInput
	// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
	ManagedBy pulumi.StringPtrInput
	// The name of the Prediction Environment.
	Name pulumi.StringPtrInput
	// The platform for the Prediction Environment.
	Platform pulumi.StringInput
	// The list of supported model formats.
	SupportedModelFormats pulumi.StringArrayInput
}

func (PredictionEnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*predictionEnvironmentArgs)(nil)).Elem()
}

type PredictionEnvironmentInput interface {
	pulumi.Input

	ToPredictionEnvironmentOutput() PredictionEnvironmentOutput
	ToPredictionEnvironmentOutputWithContext(ctx context.Context) PredictionEnvironmentOutput
}

func (*PredictionEnvironment) ElementType() reflect.Type {
	return reflect.TypeOf((**PredictionEnvironment)(nil)).Elem()
}

func (i *PredictionEnvironment) ToPredictionEnvironmentOutput() PredictionEnvironmentOutput {
	return i.ToPredictionEnvironmentOutputWithContext(context.Background())
}

func (i *PredictionEnvironment) ToPredictionEnvironmentOutputWithContext(ctx context.Context) PredictionEnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PredictionEnvironmentOutput)
}

// PredictionEnvironmentArrayInput is an input type that accepts PredictionEnvironmentArray and PredictionEnvironmentArrayOutput values.
// You can construct a concrete instance of `PredictionEnvironmentArrayInput` via:
//
//	PredictionEnvironmentArray{ PredictionEnvironmentArgs{...} }
type PredictionEnvironmentArrayInput interface {
	pulumi.Input

	ToPredictionEnvironmentArrayOutput() PredictionEnvironmentArrayOutput
	ToPredictionEnvironmentArrayOutputWithContext(context.Context) PredictionEnvironmentArrayOutput
}

type PredictionEnvironmentArray []PredictionEnvironmentInput

func (PredictionEnvironmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PredictionEnvironment)(nil)).Elem()
}

func (i PredictionEnvironmentArray) ToPredictionEnvironmentArrayOutput() PredictionEnvironmentArrayOutput {
	return i.ToPredictionEnvironmentArrayOutputWithContext(context.Background())
}

func (i PredictionEnvironmentArray) ToPredictionEnvironmentArrayOutputWithContext(ctx context.Context) PredictionEnvironmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PredictionEnvironmentArrayOutput)
}

// PredictionEnvironmentMapInput is an input type that accepts PredictionEnvironmentMap and PredictionEnvironmentMapOutput values.
// You can construct a concrete instance of `PredictionEnvironmentMapInput` via:
//
//	PredictionEnvironmentMap{ "key": PredictionEnvironmentArgs{...} }
type PredictionEnvironmentMapInput interface {
	pulumi.Input

	ToPredictionEnvironmentMapOutput() PredictionEnvironmentMapOutput
	ToPredictionEnvironmentMapOutputWithContext(context.Context) PredictionEnvironmentMapOutput
}

type PredictionEnvironmentMap map[string]PredictionEnvironmentInput

func (PredictionEnvironmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PredictionEnvironment)(nil)).Elem()
}

func (i PredictionEnvironmentMap) ToPredictionEnvironmentMapOutput() PredictionEnvironmentMapOutput {
	return i.ToPredictionEnvironmentMapOutputWithContext(context.Background())
}

func (i PredictionEnvironmentMap) ToPredictionEnvironmentMapOutputWithContext(ctx context.Context) PredictionEnvironmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PredictionEnvironmentMapOutput)
}

type PredictionEnvironmentOutput struct{ *pulumi.OutputState }

func (PredictionEnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PredictionEnvironment)(nil)).Elem()
}

func (o PredictionEnvironmentOutput) ToPredictionEnvironmentOutput() PredictionEnvironmentOutput {
	return o
}

func (o PredictionEnvironmentOutput) ToPredictionEnvironmentOutputWithContext(ctx context.Context) PredictionEnvironmentOutput {
	return o
}

// The maximum number of concurrent batch prediction jobs.
func (o PredictionEnvironmentOutput) BatchJobsMaxConcurrent() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.IntPtrOutput { return v.BatchJobsMaxConcurrent }).(pulumi.IntPtrOutput)
}

// The importance of batch jobs.
func (o PredictionEnvironmentOutput) BatchJobsPriority() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringPtrOutput { return v.BatchJobsPriority }).(pulumi.StringPtrOutput)
}

// The ID of the credential associated with the data connection. Only applicable for external prediction environments managed by DataRobot.
func (o PredictionEnvironmentOutput) CredentialId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringPtrOutput { return v.CredentialId }).(pulumi.StringPtrOutput)
}

// The ID of the data store connection configuration. Only applicable for external prediction environments managed by DataRobot.
func (o PredictionEnvironmentOutput) DatastoreId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringPtrOutput { return v.DatastoreId }).(pulumi.StringPtrOutput)
}

// The description of the Prediction Environment.
func (o PredictionEnvironmentOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Determines if the prediction environment should be managed by the management agent, datarobot, or self-managed. Self-managed by default.
func (o PredictionEnvironmentOutput) ManagedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringOutput { return v.ManagedBy }).(pulumi.StringOutput)
}

// The name of the Prediction Environment.
func (o PredictionEnvironmentOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The platform for the Prediction Environment.
func (o PredictionEnvironmentOutput) Platform() pulumi.StringOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringOutput { return v.Platform }).(pulumi.StringOutput)
}

// The list of supported model formats.
func (o PredictionEnvironmentOutput) SupportedModelFormats() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PredictionEnvironment) pulumi.StringArrayOutput { return v.SupportedModelFormats }).(pulumi.StringArrayOutput)
}

type PredictionEnvironmentArrayOutput struct{ *pulumi.OutputState }

func (PredictionEnvironmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PredictionEnvironment)(nil)).Elem()
}

func (o PredictionEnvironmentArrayOutput) ToPredictionEnvironmentArrayOutput() PredictionEnvironmentArrayOutput {
	return o
}

func (o PredictionEnvironmentArrayOutput) ToPredictionEnvironmentArrayOutputWithContext(ctx context.Context) PredictionEnvironmentArrayOutput {
	return o
}

func (o PredictionEnvironmentArrayOutput) Index(i pulumi.IntInput) PredictionEnvironmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PredictionEnvironment {
		return vs[0].([]*PredictionEnvironment)[vs[1].(int)]
	}).(PredictionEnvironmentOutput)
}

type PredictionEnvironmentMapOutput struct{ *pulumi.OutputState }

func (PredictionEnvironmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PredictionEnvironment)(nil)).Elem()
}

func (o PredictionEnvironmentMapOutput) ToPredictionEnvironmentMapOutput() PredictionEnvironmentMapOutput {
	return o
}

func (o PredictionEnvironmentMapOutput) ToPredictionEnvironmentMapOutputWithContext(ctx context.Context) PredictionEnvironmentMapOutput {
	return o
}

func (o PredictionEnvironmentMapOutput) MapIndex(k pulumi.StringInput) PredictionEnvironmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PredictionEnvironment {
		return vs[0].(map[string]*PredictionEnvironment)[vs[1].(string)]
	}).(PredictionEnvironmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PredictionEnvironmentInput)(nil)).Elem(), &PredictionEnvironment{})
	pulumi.RegisterInputType(reflect.TypeOf((*PredictionEnvironmentArrayInput)(nil)).Elem(), PredictionEnvironmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PredictionEnvironmentMapInput)(nil)).Elem(), PredictionEnvironmentMap{})
	pulumi.RegisterOutputType(PredictionEnvironmentOutput{})
	pulumi.RegisterOutputType(PredictionEnvironmentArrayOutput{})
	pulumi.RegisterOutputType(PredictionEnvironmentMapOutput{})
}
