// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class ApplicationSourceResources
    {
        /// <summary>
        /// The replicas for the Application Source.
        /// </summary>
        public readonly int? Replicas;
        /// <summary>
        /// The resource label for the Application Source.
        /// </summary>
        public readonly string? ResourceLabel;
        /// <summary>
        /// The session affinity for the Application Source.
        /// </summary>
        public readonly bool? SessionAffinity;

        [OutputConstructor]
        private ApplicationSourceResources(
            int? replicas,

            string? resourceLabel,

            bool? sessionAffinity)
        {
            Replicas = replicas;
            ResourceLabel = resourceLabel;
            SessionAffinity = sessionAffinity;
        }
    }
}
