// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class ArtifactSpecContainerGroupContainerBuild
    {
        /// <summary>
        /// Artifact image build ID.
        /// </summary>
        public readonly string? ArtifactImageBuildId;
        /// <summary>
        /// Build creation timestamp (UTC).
        /// </summary>
        public readonly string? CreatedAt;
        /// <summary>
        /// Image build status. With `source.wait_for_build` enabled (the default) this is the terminal status of the build the provider waited on; otherwise it is the status at submit time.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private ArtifactSpecContainerGroupContainerBuild(
            string? artifactImageBuildId,

            string? createdAt,

            string? status)
        {
            ArtifactImageBuildId = artifactImageBuildId;
            CreatedAt = createdAt;
            Status = status;
        }
    }
}
