// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class ArtifactSpec
    {
        /// <summary>
        /// Turns on agent-to-agent (A2A) card management and the A2A surface for this agent. Valid only when &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`agent`" pulumi-lang-dotnet="`Agent`" pulumi-lang-go="`agent`" pulumi-lang-python="`agent`" pulumi-lang-yaml="`agent`" pulumi-lang-java="`agent`" pulumi-lang-hcl="`agent`"&gt;`agent`&lt;/span&gt;. Defaults to off in the Workload API.
        /// </summary>
        public readonly bool? A2aEnabled;
        /// <summary>
        /// List of container groups.
        /// </summary>
        public readonly ImmutableArray<Outputs.ArtifactSpecContainerGroup> ContainerGroups;

        [OutputConstructor]
        private ArtifactSpec(
            bool? a2aEnabled,

            ImmutableArray<Outputs.ArtifactSpecContainerGroup> containerGroups)
        {
            A2aEnabled = a2aEnabled;
            ContainerGroups = containerGroups;
        }
    }
}
