// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class BatchPredictionJobDefinitionCsvSettings
    {
        /// <summary>
        /// Fields are delimited by this character. Use the string tab to denote TSV (TAB separated values). Must be either a one-character string or the string tab.
        /// </summary>
        public readonly string? Delimiter;
        /// <summary>
        /// Encoding for the CSV files.
        /// </summary>
        public readonly string? Encoding;
        /// <summary>
        /// Fields containing the delimiter must be quoted using this character.
        /// </summary>
        public readonly string? Quotechar;

        [OutputConstructor]
        private BatchPredictionJobDefinitionCsvSettings(
            string? delimiter,

            string? encoding,

            string? quotechar)
        {
            Delimiter = delimiter;
            Encoding = encoding;
            Quotechar = quotechar;
        }
    }
}
