// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class CustomModelTag
    {
        /// <summary>
        /// The name of the tag.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The value of the tag.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private CustomModelTag(
            string name,

            string value)
        {
            Name = name;
            Value = value;
        }
    }
}
