// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class CustomMetricJobFile
    {
        /// <summary>
        /// Path in the job.
        /// </summary>
        public readonly string Destination;
        /// <summary>
        /// Local filesystem path.
        /// </summary>
        public readonly string Source;

        [OutputConstructor]
        private CustomMetricJobFile(
            string destination,

            string source)
        {
            Destination = destination;
            Source = source;
        }
    }
}
