// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class GetArtifactsArtifactSpecContainerGroupContainerEnvironmentVarResult
    {
        /// <summary>
        /// DataRobot credential ID when source is "dr-credential".
        /// </summary>
        public readonly string DrCredentialId;
        /// <summary>
        /// Key within the credential when source is "dr-credential".
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Name of the environment variable. May be absent for "api-key" entries, in which case the token is injected as DATAROBOT*API*TOKEN.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Source type: "string" for plain text values, "dr-credential" for DataRobot credentials, or "api-key" for a platform-managed per-workload DataRobot API token.
        /// </summary>
        public readonly string Source;
        /// <summary>
        /// Value of the environment variable when source is "string".
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetArtifactsArtifactSpecContainerGroupContainerEnvironmentVarResult(
            string drCredentialId,

            string key,

            string name,

            string source,

            string value)
        {
            DrCredentialId = drCredentialId;
            Key = key;
            Name = name;
            Source = source;
            Value = value;
        }
    }
}
