// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class GetArtifactCreatorResult
    {
        /// <summary>
        /// User email address.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// User's full name.
        /// </summary>
        public readonly string FullName;
        /// <summary>
        /// User ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// User's gravatar hash.
        /// </summary>
        public readonly string Userhash;
        /// <summary>
        /// Username.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetArtifactCreatorResult(
            string email,

            string fullName,

            string id,

            string userhash,

            string username)
        {
            Email = email;
            FullName = fullName;
            Id = id;
            Userhash = userhash;
            Username = username;
        }
    }
}
