// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Outputs
{

    [OutputType]
    public sealed class WorkloadRuntimeAutoscaling
    {
        /// <summary>
        /// Whether autoscaling is enabled. Defaults to true.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Scaling policies that define when and how to scale.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkloadRuntimeAutoscalingPolicy> Policies;

        [OutputConstructor]
        private WorkloadRuntimeAutoscaling(
            bool? enabled,

            ImmutableArray<Outputs.WorkloadRuntimeAutoscalingPolicy> policies)
        {
            Enabled = enabled;
            Policies = policies;
        }
    }
}
