# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['QuotaArgs', 'Quota']

@pulumi.input_type
class QuotaArgs:
    def __init__(__self__, *,
                 default_rules: pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]],
                 resource_id: pulumi.Input[builtins.str],
                 resource_type: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a Quota resource.
        :param pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]] default_rules: The default rate-limit rules applied to all consumers.
        :param pulumi.Input[builtins.str] resource_id: The ID of the resource (e.g. the Deployment) the quota governs.
        :param pulumi.Input[builtins.str] resource_type: The type of resource the quota governs. Defaults to `deployment`.
        """
        pulumi.set(__self__, "default_rules", default_rules)
        pulumi.set(__self__, "resource_id", resource_id)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)

    @property
    @pulumi.getter(name="defaultRules")
    def default_rules(self) -> pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]]:
        """
        The default rate-limit rules applied to all consumers.
        """
        return pulumi.get(self, "default_rules")

    @default_rules.setter
    def default_rules(self, value: pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]]):
        pulumi.set(self, "default_rules", value)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Input[builtins.str]:
        """
        The ID of the resource (e.g. the Deployment) the quota governs.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The type of resource the quota governs. Defaults to `deployment`.
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "resource_type", value)


@pulumi.input_type
class _QuotaState:
    def __init__(__self__, *,
                 default_rules: Optional[pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]]] = None,
                 resource_id: Optional[pulumi.Input[builtins.str]] = None,
                 resource_type: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering Quota resources.
        :param pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]] default_rules: The default rate-limit rules applied to all consumers.
        :param pulumi.Input[builtins.str] resource_id: The ID of the resource (e.g. the Deployment) the quota governs.
        :param pulumi.Input[builtins.str] resource_type: The type of resource the quota governs. Defaults to `deployment`.
        """
        if default_rules is not None:
            pulumi.set(__self__, "default_rules", default_rules)
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)

    @property
    @pulumi.getter(name="defaultRules")
    def default_rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]]]:
        """
        The default rate-limit rules applied to all consumers.
        """
        return pulumi.get(self, "default_rules")

    @default_rules.setter
    def default_rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['QuotaDefaultRuleArgs']]]]):
        pulumi.set(self, "default_rules", value)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The ID of the resource (e.g. the Deployment) the quota governs.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The type of resource the quota governs. Defaults to `deployment`.
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "resource_type", value)


class Quota(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Union['QuotaDefaultRuleArgs', 'QuotaDefaultRuleArgsDict']]]]] = None,
                 resource_id: Optional[pulumi.Input[builtins.str]] = None,
                 resource_type: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        A usage quota governing a DataRobot resource (e.g. a Deployment). The default rules cap throughput per time window and apply to every consumer. There is at most one quota per resource; changing the resource it governs forces a new quota.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_datarobot as datarobot

        example = datarobot.Quota("example",
            resource_id="5e7e6a3f8e7d8c0001a1b2c3",
            resource_type="deployment",
            default_rules=[
                {
                    "rule": "requests",
                    "limit": 750,
                    "window": "day",
                },
                {
                    "rule": "token",
                    "limit": 100000000,
                    "window": "day",
                },
            ])
        pulumi.export("exampleId", example.id)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['QuotaDefaultRuleArgs', 'QuotaDefaultRuleArgsDict']]]] default_rules: The default rate-limit rules applied to all consumers.
        :param pulumi.Input[builtins.str] resource_id: The ID of the resource (e.g. the Deployment) the quota governs.
        :param pulumi.Input[builtins.str] resource_type: The type of resource the quota governs. Defaults to `deployment`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QuotaArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A usage quota governing a DataRobot resource (e.g. a Deployment). The default rules cap throughput per time window and apply to every consumer. There is at most one quota per resource; changing the resource it governs forces a new quota.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_datarobot as datarobot

        example = datarobot.Quota("example",
            resource_id="5e7e6a3f8e7d8c0001a1b2c3",
            resource_type="deployment",
            default_rules=[
                {
                    "rule": "requests",
                    "limit": 750,
                    "window": "day",
                },
                {
                    "rule": "token",
                    "limit": 100000000,
                    "window": "day",
                },
            ])
        pulumi.export("exampleId", example.id)
        ```

        :param str resource_name: The name of the resource.
        :param QuotaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QuotaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Union['QuotaDefaultRuleArgs', 'QuotaDefaultRuleArgsDict']]]]] = None,
                 resource_id: Optional[pulumi.Input[builtins.str]] = None,
                 resource_type: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QuotaArgs.__new__(QuotaArgs)

            if default_rules is None and not opts.urn:
                raise TypeError("Missing required property 'default_rules'")
            __props__.__dict__["default_rules"] = default_rules
            if resource_id is None and not opts.urn:
                raise TypeError("Missing required property 'resource_id'")
            __props__.__dict__["resource_id"] = resource_id
            __props__.__dict__["resource_type"] = resource_type
        super(Quota, __self__).__init__(
            'datarobot:index/quota:Quota',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            default_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Union['QuotaDefaultRuleArgs', 'QuotaDefaultRuleArgsDict']]]]] = None,
            resource_id: Optional[pulumi.Input[builtins.str]] = None,
            resource_type: Optional[pulumi.Input[builtins.str]] = None) -> 'Quota':
        """
        Get an existing Quota resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['QuotaDefaultRuleArgs', 'QuotaDefaultRuleArgsDict']]]] default_rules: The default rate-limit rules applied to all consumers.
        :param pulumi.Input[builtins.str] resource_id: The ID of the resource (e.g. the Deployment) the quota governs.
        :param pulumi.Input[builtins.str] resource_type: The type of resource the quota governs. Defaults to `deployment`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QuotaState.__new__(_QuotaState)

        __props__.__dict__["default_rules"] = default_rules
        __props__.__dict__["resource_id"] = resource_id
        __props__.__dict__["resource_type"] = resource_type
        return Quota(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="defaultRules")
    def default_rules(self) -> pulumi.Output[Sequence['outputs.QuotaDefaultRule']]:
        """
        The default rate-limit rules applied to all consumers.
        """
        return pulumi.get(self, "default_rules")

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Output[builtins.str]:
        """
        The ID of the resource (e.g. the Deployment) the quota governs.
        """
        return pulumi.get(self, "resource_id")

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> pulumi.Output[builtins.str]:
        """
        The type of resource the quota governs. Defaults to `deployment`.
        """
        return pulumi.get(self, "resource_type")

