// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApplicationSourceFromTemplateResources {
    /**
     * Path used by the Kubernetes liveness and readiness probes. When set, takes precedence over the path derived from <span pulumi-lang-nodejs="`serviceWebRequestsOnRootPath`" pulumi-lang-dotnet="`ServiceWebRequestsOnRootPath`" pulumi-lang-go="`serviceWebRequestsOnRootPath`" pulumi-lang-python="`service_web_requests_on_root_path`" pulumi-lang-yaml="`serviceWebRequestsOnRootPath`" pulumi-lang-java="`serviceWebRequestsOnRootPath`" pulumi-lang-hcl="`service_web_requests_on_root_path`">`serviceWebRequestsOnRootPath`</span>. Use this to expose a dedicated health endpoint (e.g. `/healthz`) instead of probing the root path.
     */
    healthEndpointPath?: pulumi.Input<string | undefined>;
    /**
     * The number of replicas for the Application Source. Computed by API if not specified.
     */
    replicas?: pulumi.Input<number | undefined>;
    /**
     * The resource label for the Application Source (e.g., 'cpu.small', 'cpu.medium'). Computed by API if not specified.
     */
    resourceLabel?: pulumi.Input<string | undefined>;
    /**
     * Whether to service web requests on the root path for the Application Source. Computed by API if not specified.
     */
    serviceWebRequestsOnRootPath?: pulumi.Input<boolean | undefined>;
    /**
     * Whether session affinity is enabled for the Application Source. Computed by API if not specified.
     */
    sessionAffinity?: pulumi.Input<boolean | undefined>;
}

export interface ApplicationSourceFromTemplateRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface ApplicationSourceResources {
    /**
     * Path used by the Kubernetes liveness and readiness probes. When set, takes precedence over the path derived from <span pulumi-lang-nodejs="`serviceWebRequestsOnRootPath`" pulumi-lang-dotnet="`ServiceWebRequestsOnRootPath`" pulumi-lang-go="`serviceWebRequestsOnRootPath`" pulumi-lang-python="`service_web_requests_on_root_path`" pulumi-lang-yaml="`serviceWebRequestsOnRootPath`" pulumi-lang-java="`serviceWebRequestsOnRootPath`" pulumi-lang-hcl="`service_web_requests_on_root_path`">`serviceWebRequestsOnRootPath`</span>. Use this to expose a dedicated health endpoint (e.g. `/healthz`) instead of probing the root path.
     */
    healthEndpointPath?: pulumi.Input<string | undefined>;
    /**
     * The number of replicas for the Application Source. Computed by API if not specified.
     */
    replicas?: pulumi.Input<number | undefined>;
    /**
     * The resource label for the Application Source (e.g., 'cpu.small', 'cpu.medium'). Computed by API if not specified.
     */
    resourceLabel?: pulumi.Input<string | undefined>;
    /**
     * Whether to service web requests on the root path for the Application Source. Computed by API if not specified.
     */
    serviceWebRequestsOnRootPath?: pulumi.Input<boolean | undefined>;
    /**
     * Whether session affinity is enabled for the Application Source. Computed by API if not specified.
     */
    sessionAffinity?: pulumi.Input<boolean | undefined>;
}

export interface ApplicationSourceRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface ArtifactSource {
    /**
     * Path to the local directory containing application source files to upload.
     */
    dir: pulumi.Input<string>;
    /**
     * SHA-256 fingerprint of uploadable files under <span pulumi-lang-nodejs="`dir`" pulumi-lang-dotnet="`Dir`" pulumi-lang-go="`dir`" pulumi-lang-python="`dir`" pulumi-lang-yaml="`dir`" pulumi-lang-java="`dir`" pulumi-lang-hcl="`dir`">`dir`</span> after `.drignore` / system excludes. Used to detect changes and skip re-upload when unchanged. Files covered by a system exclude are never part of this hash.
     */
    dirHash?: pulumi.Input<string | undefined>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> (default), if <span pulumi-lang-nodejs="`dir`" pulumi-lang-dotnet="`Dir`" pulumi-lang-go="`dir`" pulumi-lang-python="`dir`" pulumi-lang-yaml="`dir`" pulumi-lang-java="`dir`" pulumi-lang-hcl="`dir`">`dir`</span> has neither `.drignore` nor `.wapiignore`, the provider writes a default `.drignore` at the start of apply. Existing ignore files are never overwritten. Set to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> to skip autogeneration. System excludes always apply and cannot be re-enabled from `.drignore`: `.datarobot.yaml`, `.git`, `.gitignore`, `.wapi`, `.datarobot/workload`, and Terraform's own `.terraform`, `terraform.tfstate*` and `*.tfvars` files.
     */
    generateIgnore?: pulumi.Input<boolean | undefined>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> (default), after a source upload the provider triggers an image build and polls until it completes before proceeding (for example, before locking). When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>, the build is triggered but apply does not wait for <span pulumi-lang-nodejs="`imageUri`" pulumi-lang-dotnet="`ImageUri`" pulumi-lang-go="`imageUri`" pulumi-lang-python="`image_uri`" pulumi-lang-yaml="`imageUri`" pulumi-lang-java="`imageUri`" pulumi-lang-hcl="`image_uri`">`imageUri`</span> to be populated.
     */
    waitForBuild?: pulumi.Input<boolean | undefined>;
}

export interface ArtifactSpec {
    /**
     * Turns on agent-to-agent (A2A) card management and the A2A surface for this agent. Valid only when <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`">`type`</span> is <span pulumi-lang-nodejs="`agent`" pulumi-lang-dotnet="`Agent`" pulumi-lang-go="`agent`" pulumi-lang-python="`agent`" pulumi-lang-yaml="`agent`" pulumi-lang-java="`agent`" pulumi-lang-hcl="`agent`">`agent`</span>. Defaults to off in the Workload API.
     */
    a2aEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * List of container groups.
     */
    containerGroups: pulumi.Input<pulumi.Input<inputs.ArtifactSpecContainerGroup>[]>;
}

export interface ArtifactSpecContainerGroup {
    /**
     * List of containers in this group.
     */
    containers: pulumi.Input<pulumi.Input<inputs.ArtifactSpecContainerGroupContainer>[]>;
}

export interface ArtifactSpecContainerGroupContainer {
    /**
     * Server-set image build metadata.
     */
    build?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerBuild | undefined>;
    /**
     * Description of the container.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Container entrypoint.
     */
    entrypoints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Environment variables for the container.
     */
    environmentVars?: pulumi.Input<pulumi.Input<inputs.ArtifactSpecContainerGroupContainerEnvironmentVar>[] | undefined>;
    /**
     * Configuration for server-side image builds from source code.
     */
    imageBuildConfig?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerImageBuildConfig | undefined>;
    /**
     * Docker image URI. Populated by the provider after a completed image build when <span pulumi-lang-nodejs="`source`" pulumi-lang-dotnet="`Source`" pulumi-lang-go="`source`" pulumi-lang-python="`source`" pulumi-lang-yaml="`source`" pulumi-lang-java="`source`" pulumi-lang-hcl="`source`">`source`</span> and <span pulumi-lang-nodejs="`imageBuildConfig`" pulumi-lang-dotnet="`ImageBuildConfig`" pulumi-lang-go="`imageBuildConfig`" pulumi-lang-python="`image_build_config`" pulumi-lang-yaml="`imageBuildConfig`" pulumi-lang-java="`imageBuildConfig`" pulumi-lang-hcl="`image_build_config`">`imageBuildConfig`</span> are set. May be set explicitly when not using source-driven builds.
     */
    imageUri?: pulumi.Input<string | undefined>;
    /**
     * Container liveness check configuration.
     */
    livenessProbe?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerLivenessProbe | undefined>;
    /**
     * Name of the container.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Container access port (1024-65535). Required for primary containers; omit for non-primary.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Whether this is the primary container.
     */
    primary?: pulumi.Input<boolean | undefined>;
    /**
     * Container readiness check configuration.
     */
    readinessProbe?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerReadinessProbe | undefined>;
    /**
     * Routes to expose publicly from this container. Primary containers only, at most 50. The workload root (`/`) is authenticated by default unless declared here with another policy. Route configuration is a cluster-level capability that is disabled by default: setting this on a cluster where it is not enabled fails with `Route configuration is disabled on this cluster`.
     */
    routes?: pulumi.Input<pulumi.Input<inputs.ArtifactSpecContainerGroupContainerRoute>[] | undefined>;
    /**
     * Container startup check configuration.
     */
    startupProbe?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerStartupProbe | undefined>;
}

export interface ArtifactSpecContainerGroupContainerBuild {
    /**
     * Artifact image build ID.
     */
    artifactImageBuildId?: pulumi.Input<string | undefined>;
    /**
     * Build creation timestamp (UTC).
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Image build status. With `source.wait_for_build` enabled (the default) this is the terminal status of the build the provider waited on; otherwise it is the status at submit time.
     */
    status?: pulumi.Input<string | undefined>;
}

export interface ArtifactSpecContainerGroupContainerEnvironmentVar {
    /**
     * DataRobot credential ID. Required when source is "dr-credential".
     */
    drCredentialId?: pulumi.Input<string | undefined>;
    /**
     * Key within the credential. Required when source is "dr-credential".
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Name of the environment variable. Required when source is "string" or "dr-credential". Optional for "api-key" (defaults to DATAROBOT*API*TOKEN).
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Source type: "string" for plain text values, "dr-credential" for DataRobot credentials, or "api-key" for a platform-managed per-workload DataRobot API token. Defaults to "string".
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * Value of the environment variable. Required when source is "string".
     */
    value?: pulumi.Input<string | undefined>;
}

export interface ArtifactSpecContainerGroupContainerImageBuildConfig {
    /**
     * Reference to source code in the DataRobot catalog. Optional at create; required before image build or lock. When <span pulumi-lang-nodejs="`source`" pulumi-lang-dotnet="`Source`" pulumi-lang-go="`source`" pulumi-lang-python="`source`" pulumi-lang-yaml="`source`" pulumi-lang-java="`source`" pulumi-lang-hcl="`source`">`source`</span> is set, the provider uploads `source.dir` and populates this block.
     */
    codeRef?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerImageBuildConfigCodeRef | undefined>;
    /**
     * How the Dockerfile is obtained for the image build. Defaults to using `./Dockerfile` from the source code.
     */
    dockerfile?: pulumi.Input<inputs.ArtifactSpecContainerGroupContainerImageBuildConfigDockerfile | undefined>;
}

export interface ArtifactSpecContainerGroupContainerImageBuildConfigCodeRef {
    /**
     * Files API catalog ID (24-character hex).
     */
    catalogId: pulumi.Input<string>;
    /**
     * Files API catalog version ID (24-character hex).
     */
    catalogVersionId: pulumi.Input<string>;
}

export interface ArtifactSpecContainerGroupContainerImageBuildConfigDockerfile {
    /**
     * Entrypoint baked into the generated Dockerfile CMD. Required when source is <span pulumi-lang-nodejs="`generated`" pulumi-lang-dotnet="`Generated`" pulumi-lang-go="`generated`" pulumi-lang-python="`generated`" pulumi-lang-yaml="`generated`" pulumi-lang-java="`generated`" pulumi-lang-hcl="`generated`">`generated`</span>.
     */
    entrypoints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Execution environment ID for the base Docker image. Required when source is <span pulumi-lang-nodejs="`generated`" pulumi-lang-dotnet="`Generated`" pulumi-lang-go="`generated`" pulumi-lang-python="`generated`" pulumi-lang-yaml="`generated`" pulumi-lang-java="`generated`" pulumi-lang-hcl="`generated`">`generated`</span>.
     */
    executionEnvironmentId?: pulumi.Input<string | undefined>;
    /**
     * Execution environment version ID that pins the base image. Required when source is <span pulumi-lang-nodejs="`generated`" pulumi-lang-dotnet="`Generated`" pulumi-lang-go="`generated`" pulumi-lang-python="`generated`" pulumi-lang-yaml="`generated`" pulumi-lang-java="`generated`" pulumi-lang-hcl="`generated`">`generated`</span>.
     */
    executionEnvironmentVersionId?: pulumi.Input<string | undefined>;
    /**
     * Relative path to the Dockerfile in the source code. Used when source is <span pulumi-lang-nodejs="`provided`" pulumi-lang-dotnet="`Provided`" pulumi-lang-go="`provided`" pulumi-lang-python="`provided`" pulumi-lang-yaml="`provided`" pulumi-lang-java="`provided`" pulumi-lang-hcl="`provided`">`provided`</span>. Defaults to `./Dockerfile`. Null when source is <span pulumi-lang-nodejs="`generated`" pulumi-lang-dotnet="`Generated`" pulumi-lang-go="`generated`" pulumi-lang-python="`generated`" pulumi-lang-yaml="`generated`" pulumi-lang-java="`generated`" pulumi-lang-hcl="`generated`">`generated`</span>.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * How the Dockerfile is obtained: <span pulumi-lang-nodejs="`provided`" pulumi-lang-dotnet="`Provided`" pulumi-lang-go="`provided`" pulumi-lang-python="`provided`" pulumi-lang-yaml="`provided`" pulumi-lang-java="`provided`" pulumi-lang-hcl="`provided`">`provided`</span> (from source code) or <span pulumi-lang-nodejs="`generated`" pulumi-lang-dotnet="`Generated`" pulumi-lang-go="`generated`" pulumi-lang-python="`generated`" pulumi-lang-yaml="`generated`" pulumi-lang-java="`generated`" pulumi-lang-hcl="`generated`">`generated`</span> (from an execution environment). Defaults to <span pulumi-lang-nodejs="`provided`" pulumi-lang-dotnet="`Provided`" pulumi-lang-go="`provided`" pulumi-lang-python="`provided`" pulumi-lang-yaml="`provided`" pulumi-lang-java="`provided`" pulumi-lang-hcl="`provided`">`provided`</span>.
     */
    source?: pulumi.Input<string | undefined>;
}

export interface ArtifactSpecContainerGroupContainerLivenessProbe {
    /**
     * Minimum consecutive failures for the probe to be considered failed.
     */
    failureThreshold?: pulumi.Input<number | undefined>;
    /**
     * Host name to connect to, defaults to the pod IP.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Number of seconds to wait before the first probe is executed.
     */
    initialDelaySeconds?: pulumi.Input<number | undefined>;
    /**
     * URL path to query for health check.
     */
    path: pulumi.Input<string>;
    /**
     * How often (in seconds) to perform the probe.
     */
    periodSeconds?: pulumi.Input<number | undefined>;
    /**
     * Port number to access on the container.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Scheme to use for connecting to the host (HTTP or HTTPS).
     */
    scheme?: pulumi.Input<string | undefined>;
    /**
     * Minimum consecutive successes for the probe to be considered successful after having failed.
     */
    successThreshold?: pulumi.Input<number | undefined>;
    /**
     * Number of seconds after which the probe times out.
     */
    timeoutSeconds?: pulumi.Input<number | undefined>;
}

export interface ArtifactSpecContainerGroupContainerReadinessProbe {
    /**
     * Minimum consecutive failures for the probe to be considered failed.
     */
    failureThreshold?: pulumi.Input<number | undefined>;
    /**
     * Host name to connect to, defaults to the pod IP.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Number of seconds to wait before the first probe is executed.
     */
    initialDelaySeconds?: pulumi.Input<number | undefined>;
    /**
     * URL path to query for health check.
     */
    path: pulumi.Input<string>;
    /**
     * How often (in seconds) to perform the probe.
     */
    periodSeconds?: pulumi.Input<number | undefined>;
    /**
     * Port number to access on the container.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Scheme to use for connecting to the host (HTTP or HTTPS).
     */
    scheme?: pulumi.Input<string | undefined>;
    /**
     * Minimum consecutive successes for the probe to be considered successful after having failed.
     */
    successThreshold?: pulumi.Input<number | undefined>;
    /**
     * Number of seconds after which the probe times out.
     */
    timeoutSeconds?: pulumi.Input<number | undefined>;
}

export interface ArtifactSpecContainerGroupContainerRoute {
    /**
     * Authentication applied to this route: "required" rejects unauthenticated requests, "optional" authenticates when an Authorization header is present, "disabled" never attempts authentication.
     */
    auth: pulumi.Input<string>;
    /**
     * Route path relative to the workload root, excluding the URL prefix the workload is mounted on. Must start with `/` and be at most 1024 characters. Paths must be unique within a container.
     */
    path: pulumi.Input<string>;
}

export interface ArtifactSpecContainerGroupContainerStartupProbe {
    /**
     * Minimum consecutive failures for the probe to be considered failed.
     */
    failureThreshold?: pulumi.Input<number | undefined>;
    /**
     * Host name to connect to, defaults to the pod IP.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Number of seconds to wait before the first probe is executed.
     */
    initialDelaySeconds?: pulumi.Input<number | undefined>;
    /**
     * URL path to query for health check.
     */
    path: pulumi.Input<string>;
    /**
     * How often (in seconds) to perform the probe.
     */
    periodSeconds?: pulumi.Input<number | undefined>;
    /**
     * Port number to access on the container.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Scheme to use for connecting to the host (HTTP or HTTPS).
     */
    scheme?: pulumi.Input<string | undefined>;
    /**
     * Minimum consecutive successes for the probe to be considered successful after having failed.
     */
    successThreshold?: pulumi.Input<number | undefined>;
    /**
     * Number of seconds after which the probe times out.
     */
    timeoutSeconds?: pulumi.Input<number | undefined>;
}

export interface BatchPredictionJobDefinitionCsvSettings {
    /**
     * Fields are delimited by this character. Use the string tab to denote TSV (TAB separated values). Must be either a one-character string or the string tab.
     */
    delimiter?: pulumi.Input<string | undefined>;
    /**
     * Encoding for the CSV files.
     */
    encoding?: pulumi.Input<string | undefined>;
    /**
     * Fields containing the delimiter must be quoted using this character.
     */
    quotechar?: pulumi.Input<string | undefined>;
}

export interface BatchPredictionJobDefinitionIntakeSettings {
    /**
     * The name of specified database catalog for JDBC type.
     */
    catalog?: pulumi.Input<string | undefined>;
    /**
     * The ID of the credentials for S3 or JDBC data source.
     */
    credentialId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the external data store connected to the JDBC data source.
     */
    dataStoreId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the dataset to score for dataset type.
     */
    datasetId?: pulumi.Input<string | undefined>;
    /**
     * Any non-default endpoint URL for S3 access.
     */
    endpointUrl?: pulumi.Input<string | undefined>;
    /**
     * Changing the fetchSize can be used to balance throughput and memory usage for JDBC type.
     */
    fetchSize?: pulumi.Input<number | undefined>;
    /**
     * String path to file of scoring data for localFile type.
     */
    file?: pulumi.Input<string | undefined>;
    /**
     * A self-supplied SELECT statement of the data set you wish to predict for JDBC type.
     */
    query?: pulumi.Input<string | undefined>;
    /**
     * The name of specified database schema for JDBC type.
     */
    schema?: pulumi.Input<string | undefined>;
    /**
     * The name of specified database table for JDBC type.
     */
    table?: pulumi.Input<string | undefined>;
    /**
     * Type of data source.
     */
    type: pulumi.Input<string>;
    /**
     * The URL to score (e.g.: s3://bucket/key) for S3 type.
     */
    url?: pulumi.Input<string | undefined>;
}

export interface BatchPredictionJobDefinitionOutputSettings {
    /**
     * The name of specified database catalog for JDBC type.
     */
    catalog?: pulumi.Input<string | undefined>;
    /**
     * If no existing table is detected, attempt to create it before writing data for JDBC type.
     */
    createTableIfNotExists?: pulumi.Input<boolean | undefined>;
    /**
     * The ID of the credentials for S3 or JDBC data source.
     */
    credentialId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the external data store connected to the JDBC data source.
     */
    dataStoreId?: pulumi.Input<string | undefined>;
    /**
     * Any non-default endpoint URL for S3 access.
     */
    endpointUrl?: pulumi.Input<string | undefined>;
    /**
     * Path to save the scored data as CSV for localFile type.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * The name of specified database schema for JDBC type.
     */
    schema?: pulumi.Input<string | undefined>;
    /**
     * The type of insertion statement to create for JDBC type.
     */
    statementType?: pulumi.Input<string | undefined>;
    /**
     * The name of specified database table for JDBC type.
     */
    table?: pulumi.Input<string | undefined>;
    /**
     * Type of output.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * A list of strings containing those column names to be updated for JDBC type.
     */
    updateColumns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The URL for storing the results (e.g.: s3://bucket/key) for S3 type.
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * A list of strings containing those column names to be selected for JDBC type.
     */
    whereColumns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface BatchPredictionJobDefinitionPredictionInstance {
    /**
     * By default, prediction requests will use the API key of the user that created the job. This allows you to make requests on behalf of other users.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * If running a job against a prediction instance in the Managed AI Cloud, you must provide the organization level DataRobot-Key.
     */
    datarobotKey?: pulumi.Input<string | undefined>;
    /**
     * Hostname of the prediction instance.
     */
    hostName: pulumi.Input<string>;
    /**
     * Set to false to run prediction requests from the batch prediction job without SSL. Defaults to true.
     */
    sslEnabled?: pulumi.Input<boolean | undefined>;
}

export interface BatchPredictionJobDefinitionSchedule {
    /**
     * Days of the month when the job will run.
     */
    dayOfMonths: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Days of the week when the job will run.
     */
    dayOfWeeks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Hours of the day when the job will run.
     */
    hours: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes of the day when the job will run.
     */
    minutes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Months of the year when the job will run.
     */
    months: pulumi.Input<pulumi.Input<string>[]>;
}

export interface BatchPredictionJobDefinitionTimeseriesSettings {
    /**
     * Forecast point for the dataset, used for the forecast predictions. May be passed if timeseries_settings.type=forecast.
     */
    forecastPoint?: pulumi.Input<string | undefined>;
    /**
     * End date for historical predictions. May be passed if timeseries_settings.type=historical.
     */
    predictionsEndDate?: pulumi.Input<string | undefined>;
    /**
     * Start date for historical predictions. May be passed if timeseries_settings.type=historical.
     */
    predictionsStartDate?: pulumi.Input<string | undefined>;
    /**
     * If True, missing values in the known in advance features are allowed in the forecast window at the prediction time. Default is False.
     */
    relaxKnownInAdvanceFeaturesCheck?: pulumi.Input<boolean | undefined>;
    /**
     * Type of time-series prediction. Must be 'forecast' or 'historical'. Default is 'forecast'.
     */
    type?: pulumi.Input<string | undefined>;
}

export interface CustomApplicationFromEnvironmentResources {
    /**
     * Path used by the Kubernetes liveness and readiness probes. When set, takes precedence over the path derived from <span pulumi-lang-nodejs="`serviceWebRequestsOnRootPath`" pulumi-lang-dotnet="`ServiceWebRequestsOnRootPath`" pulumi-lang-go="`serviceWebRequestsOnRootPath`" pulumi-lang-python="`service_web_requests_on_root_path`" pulumi-lang-yaml="`serviceWebRequestsOnRootPath`" pulumi-lang-java="`serviceWebRequestsOnRootPath`" pulumi-lang-hcl="`service_web_requests_on_root_path`">`serviceWebRequestsOnRootPath`</span>. Use this to expose a dedicated health endpoint (e.g. `/healthz`) instead of probing the root path.
     */
    healthEndpointPath?: pulumi.Input<string | undefined>;
    /**
     * The number of replicas for the Custom Application. Computed by API if not specified.
     */
    replicas?: pulumi.Input<number | undefined>;
    /**
     * The resource label for the Custom Application (e.g., 'cpu.small', 'cpu.medium'). Computed by API if not specified.
     */
    resourceLabel?: pulumi.Input<string | undefined>;
    /**
     * Whether to service web requests on the root path for the Custom Application. Computed by API if not specified.
     */
    serviceWebRequestsOnRootPath?: pulumi.Input<boolean | undefined>;
    /**
     * Whether session affinity is enabled for the Custom Application. Computed by API if not specified.
     */
    sessionAffinity?: pulumi.Input<boolean | undefined>;
}

export interface CustomApplicationResources {
    /**
     * Path used by the Kubernetes liveness and readiness probes. When set, takes precedence over the path derived from <span pulumi-lang-nodejs="`serviceWebRequestsOnRootPath`" pulumi-lang-dotnet="`ServiceWebRequestsOnRootPath`" pulumi-lang-go="`serviceWebRequestsOnRootPath`" pulumi-lang-python="`service_web_requests_on_root_path`" pulumi-lang-yaml="`serviceWebRequestsOnRootPath`" pulumi-lang-java="`serviceWebRequestsOnRootPath`" pulumi-lang-hcl="`service_web_requests_on_root_path`">`serviceWebRequestsOnRootPath`</span>. Use this to expose a dedicated health endpoint (e.g. `/healthz`) instead of probing the root path.
     */
    healthEndpointPath?: pulumi.Input<string | undefined>;
    /**
     * The number of replicas for the Custom Application. Computed by API if not specified.
     */
    replicas?: pulumi.Input<number | undefined>;
    /**
     * The resource label for the Custom Application (e.g., 'cpu.small', 'cpu.medium'). Computed by API if not specified.
     */
    resourceLabel?: pulumi.Input<string | undefined>;
    /**
     * Whether to service web requests on the root path for the Custom Application. Computed by API if not specified.
     */
    serviceWebRequestsOnRootPath?: pulumi.Input<boolean | undefined>;
    /**
     * Whether session affinity is enabled for the Custom Application. Computed by API if not specified.
     */
    sessionAffinity?: pulumi.Input<boolean | undefined>;
}

export interface CustomJobRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface CustomJobSchedule {
    /**
     * Days of the month when the job will run.
     */
    dayOfMonths: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Days of the week when the job will run.
     */
    dayOfWeeks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Hours of the day when the job will run.
     */
    hours: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes of the day when the job will run.
     */
    minutes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Months of the year when the job will run.
     */
    months: pulumi.Input<pulumi.Input<string>[]>;
}

export interface CustomMetricBatch {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
}

export interface CustomMetricFromJobBatch {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
}

export interface CustomMetricFromJobParameterOverride {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface CustomMetricFromJobSampleCount {
    /**
     * Column name.
     */
    columnName: pulumi.Input<string>;
}

export interface CustomMetricFromJobSchedule {
    /**
     * Days of the month when the metric job will run.
     */
    dayOfMonths: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Days of the week when the metric job will run.
     */
    dayOfWeeks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Hours of the day when the metric job will run.
     */
    hours: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes of the day when the metric job will run.
     */
    minutes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Months of the year when the metric job will run.
     */
    months: pulumi.Input<pulumi.Input<string>[]>;
}

export interface CustomMetricFromJobTimestamp {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
    /**
     * Format.
     */
    timeFormat?: pulumi.Input<string | undefined>;
}

export interface CustomMetricFromJobValue {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
}

export interface CustomMetricJobRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface CustomMetricSampleCount {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
}

export interface CustomMetricTimestamp {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
    /**
     * Format.
     */
    timeFormat?: pulumi.Input<string | undefined>;
}

export interface CustomMetricValue {
    /**
     * Column name.
     */
    columnName?: pulumi.Input<string | undefined>;
}

export interface CustomModelGuardConfiguration {
    /**
     * Additional guard configuration
     */
    additionalGuardConfig?: pulumi.Input<inputs.CustomModelGuardConfigurationAdditionalGuardConfig | undefined>;
    /**
     * The deployment ID of this guard.
     */
    deploymentId?: pulumi.Input<string | undefined>;
    /**
     * The input column name of this guard.
     */
    inputColumnName?: pulumi.Input<string | undefined>;
    /**
     * The intervention for the guard configuration.
     */
    intervention: pulumi.Input<inputs.CustomModelGuardConfigurationIntervention>;
    /**
     * The LLM type for this guard.
     */
    llmType?: pulumi.Input<string | undefined>;
    /**
     * The name of the guard configuration.
     */
    name: pulumi.Input<string>;
    /**
     * Configuration info for NeMo guards.
     */
    nemoInfo?: pulumi.Input<inputs.CustomModelGuardConfigurationNemoInfo | undefined>;
    /**
     * The OpenAI API base URL for this guard.
     */
    openaiApiBase?: pulumi.Input<string | undefined>;
    /**
     * The ID of an OpenAI credential for this guard.
     */
    openaiCredential?: pulumi.Input<string | undefined>;
    /**
     * The ID of an OpenAI deployment for this guard.
     */
    openaiDeploymentId?: pulumi.Input<string | undefined>;
    /**
     * The output column name of this guard.
     */
    outputColumnName?: pulumi.Input<string | undefined>;
    /**
     * The list of stages for the guard configuration.
     */
    stages: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The template name of the guard configuration.
     */
    templateName: pulumi.Input<string>;
}

export interface CustomModelGuardConfigurationAdditionalGuardConfig {
    /**
     * Cost metric configuration
     */
    cost?: pulumi.Input<inputs.CustomModelGuardConfigurationAdditionalGuardConfigCost | undefined>;
}

export interface CustomModelGuardConfigurationAdditionalGuardConfigCost {
    /**
     * Currency for cost calculation (USD)
     */
    currency: pulumi.Input<string>;
    /**
     * LLM Price for<span pulumi-lang-nodejs=" inputUnit " pulumi-lang-dotnet=" InputUnit " pulumi-lang-go=" inputUnit " pulumi-lang-python=" input_unit " pulumi-lang-yaml=" inputUnit " pulumi-lang-java=" inputUnit " pulumi-lang-hcl=" input_unit "> inputUnit </span>tokens
     */
    inputPrice: pulumi.Input<number>;
    /**
     * No of input tokens for given price
     */
    inputUnit: pulumi.Input<number>;
    /**
     * LLM Price for<span pulumi-lang-nodejs=" outputUnit " pulumi-lang-dotnet=" OutputUnit " pulumi-lang-go=" outputUnit " pulumi-lang-python=" output_unit " pulumi-lang-yaml=" outputUnit " pulumi-lang-java=" outputUnit " pulumi-lang-hcl=" output_unit "> outputUnit </span>tokens
     */
    outputPrice: pulumi.Input<number>;
    /**
     * No of output tokens for given price
     */
    outputUnit: pulumi.Input<number>;
}

export interface CustomModelGuardConfigurationIntervention {
    /**
     * The action of the guard intervention.
     */
    action: pulumi.Input<string>;
    /**
     * The JSON-encoded condition of the guard intervention. e.g. `{"comparand": 0.5, "comparator": "lessThan"}`
     */
    condition: pulumi.Input<string>;
    /**
     * The message of the guard intervention.
     */
    message?: pulumi.Input<string | undefined>;
}

export interface CustomModelGuardConfigurationNemoInfo {
    /**
     * The actions for the NeMo information.
     */
    actions?: pulumi.Input<string | undefined>;
    /**
     * NeMo guardrails blocked terms list.
     */
    blockedTerms?: pulumi.Input<string | undefined>;
    /**
     * NeMo guardrails prompts.
     */
    llmPrompts?: pulumi.Input<string | undefined>;
    /**
     * Overall NeMo configuration YAML.
     */
    mainConfig?: pulumi.Input<string | undefined>;
    /**
     * NeMo guardrails configuration Colang.
     */
    railsConfig?: pulumi.Input<string | undefined>;
}

export interface CustomModelOverallModerationConfiguration {
    /**
     * The timeout action of the overall moderation configuration.
     */
    timeoutAction?: pulumi.Input<string | undefined>;
    /**
     * The timeout in seconds of the overall moderation configuration.
     */
    timeoutSec?: pulumi.Input<number | undefined>;
}

export interface CustomModelRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface CustomModelSourceRemoteRepository {
    /**
     * The ID of the source remote repository.
     */
    id: pulumi.Input<string>;
    /**
     * The reference of the source remote repository.
     */
    ref: pulumi.Input<string>;
    /**
     * The list of source paths in the source remote repository.
     */
    sourcePaths: pulumi.Input<pulumi.Input<string>[]>;
}

export interface CustomModelTag {
    /**
     * The name of the tag.
     */
    name: pulumi.Input<string>;
    /**
     * The value of the tag.
     */
    value: pulumi.Input<string>;
}

export interface DatasourceParams {
    /**
     * The Catalog name in the database if supported.
     */
    catalog?: pulumi.Input<string | undefined>;
    /**
     * The id of the DataStore.
     */
    dataStoreId: pulumi.Input<string>;
    /**
     * A user specified fetch size in the range [1, 20000]. By default a fetchSize will be assigned to balance throughput and memory usage.
     */
    fetchSize?: pulumi.Input<number | undefined>;
    /**
     * The name of the partition column.
     */
    partitionColumn?: pulumi.Input<string | undefined>;
    /**
     * The user-specified path for BLOB storage.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * The user specified SQL query.
     */
    query?: pulumi.Input<string | undefined>;
    /**
     * The name of the schema associated with the table.
     */
    schema?: pulumi.Input<string | undefined>;
    /**
     * The name of specified database table.
     */
    table?: pulumi.Input<string | undefined>;
}

export interface DeploymentAssociationIdSettings {
    /**
     * Whether to auto generate ID.
     */
    autoGenerateId?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the columns to be used as association ID, currently only support a list of one string.
     */
    columnNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the association ID column is required in prediction requests.
     */
    requiredInPredictionRequests?: pulumi.Input<boolean | undefined>;
}

export interface DeploymentBatchMonitoringSettings {
    /**
     * If batch monitoring is enabled.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentBiasAndFairnessSettings {
    /**
     * A set of fairness metrics to use for calculating fairness.
     */
    fairnessMetricSet: pulumi.Input<string>;
    /**
     * Threshold value of the fairness metric. Cannot be less than 0 or greater than 1.
     */
    fairnessThreshold: pulumi.Input<number>;
    /**
     * A target value that should be treated as a positive outcome for the prediction.
     */
    preferableTargetValue: pulumi.Input<boolean>;
    /**
     * A list of features to mark as protected.
     */
    protectedFeatures: pulumi.Input<pulumi.Input<string>[]>;
}

export interface DeploymentChallengerModelsSettings {
    /**
     * Is 'True' if challenger models is enabled for this deployment.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentChallengerReplaySettings {
    /**
     * If challenger replay is enabled.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentDriftTrackingSettings {
    /**
     * If feature drift tracking is to be turned on.
     */
    featureDriftEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The feature selection method to be used for drift tracking.
     */
    featureSelection?: pulumi.Input<string | undefined>;
    /**
     * If target drift tracking is to be turned on.
     */
    targetDriftEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * List of features to be tracked for drift.
     */
    trackedFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface DeploymentFeatureCacheSettings {
    /**
     * If feature cache is enabled for this Deployment.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * If feature cache fetching is enabled.
     */
    fetching?: pulumi.Input<boolean | undefined>;
    /**
     * Defines the feature cache schedule.
     */
    schedule?: pulumi.Input<inputs.DeploymentFeatureCacheSettingsSchedule | undefined>;
}

export interface DeploymentFeatureCacheSettingsSchedule {
    /**
     * Days of the month.
     */
    dayOfMonths: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Days of the week.
     */
    dayOfWeeks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Hours of the day.
     */
    hours: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes of the day.
     */
    minutes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Months of the year.
     */
    months: pulumi.Input<pulumi.Input<string>[]>;
}

export interface DeploymentHealthSettings {
    /**
     * The accuracy health settings for this Deployment.
     */
    accuracy?: pulumi.Input<inputs.DeploymentHealthSettingsAccuracy | undefined>;
    /**
     * The actuals timeliness health settings for this Deployment.
     */
    actualsTimeliness?: pulumi.Input<inputs.DeploymentHealthSettingsActualsTimeliness | undefined>;
    /**
     * The custom metrics health settings for this Deployment.
     */
    customMetrics?: pulumi.Input<inputs.DeploymentHealthSettingsCustomMetrics | undefined>;
    /**
     * The data drift health settings for this Deployment.
     */
    dataDrift?: pulumi.Input<inputs.DeploymentHealthSettingsDataDrift | undefined>;
    /**
     * The fairness health settings for this Deployment.
     */
    fairness?: pulumi.Input<inputs.DeploymentHealthSettingsFairness | undefined>;
    /**
     * The predictions timeliness health settings for this Deployment.
     */
    predictionsTimeliness?: pulumi.Input<inputs.DeploymentHealthSettingsPredictionsTimeliness | undefined>;
    /**
     * The service health settings for this Deployment.
     */
    service?: pulumi.Input<inputs.DeploymentHealthSettingsService | undefined>;
}

export interface DeploymentHealthSettingsAccuracy {
    /**
     * The batch count for the accuracy health settings.
     */
    batchCount?: pulumi.Input<number | undefined>;
    /**
     * The failing threshold for the accuracy health settings.
     */
    failingThreshold?: pulumi.Input<number | undefined>;
    /**
     * The measurement for the accuracy health settings.
     */
    measurement?: pulumi.Input<string | undefined>;
    /**
     * The metric for the accuracy health settings.
     */
    metric?: pulumi.Input<string | undefined>;
    /**
     * The warning threshold for the accuracy health settings.
     */
    warningThreshold?: pulumi.Input<number | undefined>;
}

export interface DeploymentHealthSettingsActualsTimeliness {
    /**
     * If acutals timeliness is enabled for this Deployment.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The expected frequency for the actuals timeliness health settings.
     */
    expectedFrequency?: pulumi.Input<string | undefined>;
}

export interface DeploymentHealthSettingsCustomMetrics {
    /**
     * The failing conditions for the custom metrics health settings.
     */
    failingConditions?: pulumi.Input<pulumi.Input<inputs.DeploymentHealthSettingsCustomMetricsFailingCondition>[] | undefined>;
    /**
     * The warning conditions for the custom metrics health settings.
     */
    warningConditions?: pulumi.Input<pulumi.Input<inputs.DeploymentHealthSettingsCustomMetricsWarningCondition>[] | undefined>;
}

export interface DeploymentHealthSettingsCustomMetricsFailingCondition {
    /**
     * The compare operator for the failing condition of the custom metrics health settings.
     */
    compareOperator: pulumi.Input<string>;
    /**
     * The metric ID for the failing condition of the custom metrics health settings.
     */
    metricId: pulumi.Input<string>;
    /**
     * The threshold for the failing condition of the custom metrics health settings.
     */
    threshold: pulumi.Input<number>;
}

export interface DeploymentHealthSettingsCustomMetricsWarningCondition {
    /**
     * The compare operator for the warning condition of the custom metrics health settings.
     */
    compareOperator: pulumi.Input<string>;
    /**
     * The metric ID for the warning condition of the custom metrics health settings.
     */
    metricId: pulumi.Input<string>;
    /**
     * The threshold for the warning condition of the custom metrics health settings.
     */
    threshold: pulumi.Input<number>;
}

export interface DeploymentHealthSettingsDataDrift {
    /**
     * The batch count for the data drift health settings.
     */
    batchCount?: pulumi.Input<number | undefined>;
    /**
     * The drift threshold for the data drift health settings.
     */
    driftThreshold?: pulumi.Input<number | undefined>;
    /**
     * The exclude features for the data drift health settings.
     */
    excludeFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The high importance failing count for the data drift health settings.
     */
    highImportanceFailingCount?: pulumi.Input<number | undefined>;
    /**
     * The high importance warning count for the data drift health settings.
     */
    highImportanceWarningCount?: pulumi.Input<number | undefined>;
    /**
     * The importance threshold for the data drift health settings.
     */
    importanceThreshold?: pulumi.Input<number | undefined>;
    /**
     * The low importance failing count for the data drift health settings.
     */
    lowImportanceFailingCount?: pulumi.Input<number | undefined>;
    /**
     * The low importance warning count for the data drift health settings.
     */
    lowImportanceWarningCount?: pulumi.Input<number | undefined>;
    /**
     * The starred features for the data drift health settings.
     */
    starredFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The time interval for the data drift health settings.
     */
    timeInterval?: pulumi.Input<string | undefined>;
}

export interface DeploymentHealthSettingsFairness {
    /**
     * The protected class failing count for the fairness health settings.
     */
    protectedClassFailingCount?: pulumi.Input<number | undefined>;
    /**
     * The protected class warning count for the fairness health settings.
     */
    protectedClassWarningCount?: pulumi.Input<number | undefined>;
}

export interface DeploymentHealthSettingsPredictionsTimeliness {
    /**
     * If predictions timeliness is enabled for this Deployment.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The expected frequency for the predictions timeliness health settings.
     */
    expectedFrequency?: pulumi.Input<string | undefined>;
}

export interface DeploymentHealthSettingsService {
    /**
     * The batch count for the service health settings.
     */
    batchCount: pulumi.Input<number>;
}

export interface DeploymentPredictionIntervalsSettings {
    /**
     * Whether prediction intervals are enabled for this deployment.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * List of enabled prediction intervals’ sizes for this deployment.
     */
    percentiles?: pulumi.Input<pulumi.Input<number>[] | undefined>;
}

export interface DeploymentPredictionWarningSettings {
    /**
     * The custom boundaries for prediction warnings.
     */
    customBoundaries?: pulumi.Input<inputs.DeploymentPredictionWarningSettingsCustomBoundaries | undefined>;
    /**
     * If target prediction warning is enabled for this Deployment.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentPredictionWarningSettingsCustomBoundaries {
    /**
     * All predictions less than provided value will be considered anomalous.
     */
    lowerBoundary?: pulumi.Input<number | undefined>;
    /**
     * All predictions greater than provided value will be considered anomalous.
     */
    upperBoundary?: pulumi.Input<number | undefined>;
}

export interface DeploymentPredictionsByForecastDateSettings {
    /**
     * The column name in prediction datasets to be used as forecast date.
     */
    columnName?: pulumi.Input<string | undefined>;
    /**
     * The datetime format of the forecast date column in prediction datasets.
     */
    datetimeFormat?: pulumi.Input<string | undefined>;
    /**
     * Is ’True’ if predictions by forecast date is enabled for this deployment.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentPredictionsDataCollectionSettings {
    /**
     * If predictions data collections is enabled for this Deployment.
     */
    enabled: pulumi.Input<boolean>;
}

export interface DeploymentPredictionsSettings {
    /**
     * The maximum number of computes to use for predictions.
     */
    maxComputes?: pulumi.Input<number | undefined>;
    /**
     * The minimum number of computes to use for predictions.
     */
    minComputes?: pulumi.Input<number | undefined>;
    /**
     * The resource bundle ID to use for predictions.
     */
    resourceBundleId?: pulumi.Input<string | undefined>;
}

export interface DeploymentRetrainingPolicyAutopilotOptions {
    /**
     * Blend best models during Autopilot run. This option is not supported in SHAP-only mode.
     */
    blendBestModels?: pulumi.Input<boolean | undefined>;
    /**
     * The autopiltot mode.
     */
    mode?: pulumi.Input<string | undefined>;
    /**
     * Run Autopilot on Leakage Removed feature list (if exists).
     */
    runLeakageRemovedFeatureList?: pulumi.Input<boolean | undefined>;
    /**
     * Keep only models that can be converted to scorable java code during Autopilot run.
     */
    scoringCodeOnly?: pulumi.Input<boolean | undefined>;
    /**
     * Include only models with SHAP value support.
     */
    shapOnlyMode?: pulumi.Input<boolean | undefined>;
}

export interface DeploymentRetrainingPolicyProjectOptions {
    /**
     * The partitioning method for projects used to build new models.
     */
    cvMethod?: pulumi.Input<string | undefined>;
    /**
     * The percentage of dataset to assign to holdout set in projects used to build new models.
     */
    holdoutPct?: pulumi.Input<number | undefined>;
    /**
     * The model selection metric in projects used to build new models.
     */
    metric?: pulumi.Input<string | undefined>;
    /**
     * The number of cross validation folds to use for projects used to build new models.
     */
    reps?: pulumi.Input<number | undefined>;
    /**
     * The percentage of dataset to assign to validation set in projects used to build new models.
     */
    validationPct?: pulumi.Input<number | undefined>;
    /**
     * The validation type for projects used to build new models.
     */
    validationType?: pulumi.Input<string | undefined>;
}

export interface DeploymentRetrainingPolicyTimeSeriesOptions {
    /**
     * The ID of the calendar to be used in this project.
     */
    calendarId?: pulumi.Input<string | undefined>;
    /**
     * For time series projects only. Used to specify which differencing method to apply if the data is stationary. For classification problems simple and seasonal are not allowed. Parameter periodicities must be specified if seasonal is chosen. Defaults to auto.
     */
    differencingMethod?: pulumi.Input<string | undefined>;
    /**
     * Discount factor (alpha) used for exponentially weighted moving features.
     */
    exponentiallyWeightedMovingAlpha?: pulumi.Input<number | undefined>;
    /**
     * A list of periodicities for time series projects only. For classification problems periodicities are not allowed. If this is provided, parameter 'differencing*method' will default to 'seasonal' if not provided or 'auto'.
     */
    periodicities?: pulumi.Input<pulumi.Input<inputs.DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicity>[] | undefined>;
    /**
     * For time series projects only. Used to specify whether to treat data as exponential trend and apply transformations like log-transform. For classification problems always is not allowed. Defaults to auto.
     */
    treatAsExponential?: pulumi.Input<string | undefined>;
}

export interface DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicity {
    /**
     * The number of time steps.
     */
    timeSteps: pulumi.Input<number>;
    /**
     * The time unit or ROW if windowsBasisUnit is ROW
     */
    timeUnit: pulumi.Input<string>;
}

export interface DeploymentRetrainingPolicyTrigger {
    /**
     * Custom job ID for the retraining policy.
     */
    customJobId?: pulumi.Input<string | undefined>;
    /**
     * Minimal interval between policy runs in ISO 8601 duration string.
     */
    minIntervalBetweenRuns?: pulumi.Input<string | undefined>;
    /**
     * Schedule for the retraining policy.
     */
    schedule?: pulumi.Input<inputs.DeploymentRetrainingPolicyTriggerSchedule | undefined>;
    /**
     * Identifies when trigger type is based on deployment a health status, whether the policy will run when health status declines to failing.
     */
    statusDeclinesToFailing?: pulumi.Input<boolean | undefined>;
    /**
     * Identifies when trigger type is based on deployment a health status, whether the policy will run when health status declines to warning.
     */
    statusDeclinesToWarning?: pulumi.Input<boolean | undefined>;
    /**
     * Identifies when trigger type is based on deployment a health status, whether the policy will run when health status still in decline.
     */
    statusStillInDecline?: pulumi.Input<boolean | undefined>;
    /**
     * Type of retraining policy trigger.
     */
    type?: pulumi.Input<string | undefined>;
}

export interface DeploymentRetrainingPolicyTriggerSchedule {
    /**
     * Days of the month when the job will run.
     */
    dayOfMonths: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Days of the week when the job will run.
     */
    dayOfWeeks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Hours of the day when the job will run.
     */
    hours: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes of the day when the job will run.
     */
    minutes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Months of the year when the job will run.
     */
    months: pulumi.Input<pulumi.Input<string>[]>;
}

export interface DeploymentRetrainingSettings {
    /**
     * ID of the credential used to refresh retraining dataset.
     */
    credentialId?: pulumi.Input<string | undefined>;
    /**
     * ID of the retraining dataset.
     */
    datasetId?: pulumi.Input<string | undefined>;
    /**
     * ID of the prediction environment to associate with the challengers created by retraining policies.
     */
    predictionEnvironmentId?: pulumi.Input<string | undefined>;
    /**
     * ID of the retraining user.
     */
    retrainingUserId?: pulumi.Input<string | undefined>;
}

export interface DeploymentRuntimeParameterValue {
    /**
     * The name of the runtime parameter.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the runtime parameter.
     */
    type: pulumi.Input<string>;
    /**
     * The value of the runtime parameter (type conversion is handled internally).
     */
    value: pulumi.Input<string>;
}

export interface DeploymentSegmentAnalysisSettings {
    /**
     * A list of strings that gives the segment attributes selected for tracking.
     */
    attributes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Set to 'True' if segment analysis is enabled for this deployment.
     */
    enabled: pulumi.Input<boolean>;
}

export interface LlmBlueprintCustomModelLlmSettings {
    /**
     * The external LLM's context size, in tokens. This value is only used for pruning documents supplied to the LLM when a vector database is associated with the LLM blueprint. It does not affect the external LLM's actual context size in any way and is not supplied to the LLM.
     */
    externalLlmContextSize?: pulumi.Input<number | undefined>;
    /**
     * System prompt guides the style of the LLM response. It is a 'universal' prompt, prepended to all individual prompts.
     */
    systemPrompt?: pulumi.Input<string | undefined>;
    /**
     * The validation ID of the custom model LLM.
     */
    validationId?: pulumi.Input<string | undefined>;
}

export interface LlmBlueprintLlmSettings {
    /**
     * The ID of the custom model to use via chat completion interface.
     */
    customModelId?: pulumi.Input<string | undefined>;
    /**
     * The maximum number of tokens allowed in the completion. The combined count of this value and prompt tokens must be below the model's maximum context size, where prompt token count is comprised of system prompt, user prompt, recent chat history, and vector database citations.
     */
    maxCompletionLength?: pulumi.Input<number | undefined>;
    /**
     * Guides the style of the LLM response. It is a 'universal' prompt, prepended to all individual prompts.
     */
    systemPrompt?: pulumi.Input<string | undefined>;
    /**
     * Controls the randomness of model output, where higher values return more diverse output and lower values return more deterministic results.
     */
    temperature?: pulumi.Input<number | undefined>;
    /**
     * Threshold that controls the selection of words included in the response, based on a cumulative probability cutoff for token selection. Higher numbers return more diverse options for outputs.
     */
    topP?: pulumi.Input<number | undefined>;
}

export interface LlmBlueprintVectorDatabaseSettings {
    /**
     * The maximum number of documents to retrieve from the Vector Database.
     */
    maxDocumentsRetrievedPerPrompt?: pulumi.Input<number | undefined>;
    /**
     * The maximum number of tokens to retrieve from the Vector Database.
     */
    maxTokens?: pulumi.Input<number | undefined>;
}

export interface NotificationChannelCustomHeader {
    /**
     * The name of the header.
     */
    name: pulumi.Input<string>;
    /**
     * The value of the header.
     */
    value: pulumi.Input<string>;
}

export interface NotificationChannelDrEntity {
    /**
     * The ID of the DataRobot entity.
     */
    id: pulumi.Input<string>;
    /**
     * The name of the entity.
     */
    name: pulumi.Input<string>;
}

export interface QuotaDefaultRule {
    /**
     * The maximum allowed for <span pulumi-lang-nodejs="`rule`" pulumi-lang-dotnet="`Rule`" pulumi-lang-go="`rule`" pulumi-lang-python="`rule`" pulumi-lang-yaml="`rule`" pulumi-lang-java="`rule`" pulumi-lang-hcl="`rule`">`rule`</span> within <span pulumi-lang-nodejs="`window`" pulumi-lang-dotnet="`Window`" pulumi-lang-go="`window`" pulumi-lang-python="`window`" pulumi-lang-yaml="`window`" pulumi-lang-java="`window`" pulumi-lang-hcl="`window`">`window`</span>.
     */
    limit: pulumi.Input<number>;
    /**
     * The metric the rule limits, e.g. <span pulumi-lang-nodejs="`requests`" pulumi-lang-dotnet="`Requests`" pulumi-lang-go="`requests`" pulumi-lang-python="`requests`" pulumi-lang-yaml="`requests`" pulumi-lang-java="`requests`" pulumi-lang-hcl="`requests`">`requests`</span> or <span pulumi-lang-nodejs="`token`" pulumi-lang-dotnet="`Token`" pulumi-lang-go="`token`" pulumi-lang-python="`token`" pulumi-lang-yaml="`token`" pulumi-lang-java="`token`" pulumi-lang-hcl="`token`">`token`</span>.
     */
    rule: pulumi.Input<string>;
    /**
     * The time window the limit applies to: <span pulumi-lang-nodejs="`min`" pulumi-lang-dotnet="`Min`" pulumi-lang-go="`min`" pulumi-lang-python="`min`" pulumi-lang-yaml="`min`" pulumi-lang-java="`min`" pulumi-lang-hcl="`min`">`min`</span>, <span pulumi-lang-nodejs="`hour`" pulumi-lang-dotnet="`Hour`" pulumi-lang-go="`hour`" pulumi-lang-python="`hour`" pulumi-lang-yaml="`hour`" pulumi-lang-java="`hour`" pulumi-lang-hcl="`hour`">`hour`</span>, or <span pulumi-lang-nodejs="`day`" pulumi-lang-dotnet="`Day`" pulumi-lang-go="`day`" pulumi-lang-python="`day`" pulumi-lang-yaml="`day`" pulumi-lang-java="`day`" pulumi-lang-hcl="`day`">`day`</span>.
     */
    window: pulumi.Input<string>;
}

export interface RegisteredModelTag {
    /**
     * The name of the tag.
     */
    name: pulumi.Input<string>;
    /**
     * The value of the tag.
     */
    value: pulumi.Input<string>;
}

export interface VectorDatabaseChunkingParameters {
    /**
     * The percentage of overlap between chunks.
     */
    chunkOverlapPercentage?: pulumi.Input<number | undefined>;
    /**
     * The size of the chunks.
     */
    chunkSize?: pulumi.Input<number | undefined>;
    /**
     * The method used to chunk the data.
     */
    chunkingMethod?: pulumi.Input<string | undefined>;
    /**
     * Whether DataRobot treats each row of the dataset as a finished chunk (custom chunking) instead of running the built-in chunker. Use this when the dataset is already pre-chunked. Defaults to false.
     */
    customChunking?: pulumi.Input<boolean | undefined>;
    /**
     * The id of the Embedding Model.
     */
    embeddingModel?: pulumi.Input<string | undefined>;
    /**
     * Whether the separator is a regex.
     */
    isSeparatorRegex?: pulumi.Input<boolean | undefined>;
    /**
     * The separators used to split the data.
     */
    separators?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface WorkloadRuntime {
    /**
     * Per-group runtime configuration.
     */
    containerGroups?: pulumi.Input<pulumi.Input<inputs.WorkloadRuntimeContainerGroup>[] | undefined>;
    /**
     * Replacement policy for in-place workload replacement (rolling strategy). Applied when <span pulumi-lang-nodejs="`artifactId`" pulumi-lang-dotnet="`ArtifactId`" pulumi-lang-go="`artifactId`" pulumi-lang-python="`artifact_id`" pulumi-lang-yaml="`artifactId`" pulumi-lang-java="`artifactId`" pulumi-lang-hcl="`artifact_id`">`artifactId`</span> changes or when replacement policy settings change. Runtime-only changes use `PATCH /workloads/{id}/settings`, which does not accept custom replacement timing (WAPI uses platform defaults).
     */
    replacementPolicy?: pulumi.Input<inputs.WorkloadRuntimeReplacementPolicy | undefined>;
}

export interface WorkloadRuntimeContainerGroup {
    /**
     * Autoscaling configuration. When set, takes precedence over <span pulumi-lang-nodejs="`replicaCount`" pulumi-lang-dotnet="`ReplicaCount`" pulumi-lang-go="`replicaCount`" pulumi-lang-python="`replica_count`" pulumi-lang-yaml="`replicaCount`" pulumi-lang-java="`replicaCount`" pulumi-lang-hcl="`replica_count`">`replicaCount`</span>.
     */
    autoscaling?: pulumi.Input<inputs.WorkloadRuntimeContainerGroupAutoscaling | undefined>;
    /**
     * How to select among <span pulumi-lang-nodejs="`resourceBundles`" pulumi-lang-dotnet="`ResourceBundles`" pulumi-lang-go="`resourceBundles`" pulumi-lang-python="`resource_bundles`" pulumi-lang-yaml="`resourceBundles`" pulumi-lang-java="`resourceBundles`" pulumi-lang-hcl="`resource_bundles`">`resourceBundles`</span>. Defaults to <span pulumi-lang-nodejs="`availability`" pulumi-lang-dotnet="`Availability`" pulumi-lang-go="`availability`" pulumi-lang-python="`availability`" pulumi-lang-yaml="`availability`" pulumi-lang-java="`availability`" pulumi-lang-hcl="`availability`">`availability`</span>.
     */
    bundleSelectionPolicy?: pulumi.Input<string | undefined>;
    /**
     * Per-container resource allocation overrides.
     */
    containers?: pulumi.Input<pulumi.Input<inputs.WorkloadRuntimeContainerGroupContainer>[] | undefined>;
    /**
     * Container group name (server-assigned, always <span pulumi-lang-nodejs="`default`" pulumi-lang-dotnet="`Default`" pulumi-lang-go="`default`" pulumi-lang-python="`default`" pulumi-lang-yaml="`default`" pulumi-lang-java="`default`" pulumi-lang-hcl="`default`">`default`</span>).
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Number of replicas. Cannot be set alongside `autoscaling.enabled=true`. Set to <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to explicitly clear it.
     */
    replicaCount?: pulumi.Input<number | undefined>;
    /**
     * Ordered list of resource bundle IDs. One is selected at scheduling time.
     */
    resourceBundles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface WorkloadRuntimeContainerGroupAutoscaling {
    /**
     * Whether autoscaling is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum number of replicas. Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    maxReplicaCount?: pulumi.Input<number | undefined>;
    /**
     * Minimum number of replicas. Set to <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to allow scale-to-zero. Defaults to <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>.
     */
    minReplicaCount?: pulumi.Input<number | undefined>;
    /**
     * Scaling policies that define when and how to scale.
     */
    policies: pulumi.Input<pulumi.Input<inputs.WorkloadRuntimeContainerGroupAutoscalingPolicy>[]>;
}

export interface WorkloadRuntimeContainerGroupAutoscalingPolicy {
    /**
     * Metric used for scaling decisions: `cpuAverageUtilization`, `httpRequestsConcurrency`, `gpuCacheUtilization`, or `gpuRequestQueueDepth`. Custom metric names (e.g. `vllm:kv_cache_usage_perc`) are supported for NIM artifacts only.
     */
    scalingMetric: pulumi.Input<string>;
    /**
     * Target value for the scaling metric. Must be non-negative.
     */
    target: pulumi.Input<number>;
}

export interface WorkloadRuntimeContainerGroupContainer {
    /**
     * Container name. Must match a container declared in the artifact group.
     */
    name: pulumi.Input<string>;
    /**
     * Resource allocation for this container.
     */
    resourceAllocation?: pulumi.Input<inputs.WorkloadRuntimeContainerGroupContainerResourceAllocation | undefined>;
}

export interface WorkloadRuntimeContainerGroupContainerResourceAllocation {
    /**
     * CPU cores allocated to this container.
     */
    cpu?: pulumi.Input<number | undefined>;
    /**
     * GPUs allocated to this container.
     */
    gpu?: pulumi.Input<number | undefined>;
    /**
     * GPU VRAM allocated. Accepts human-readable strings (e.g. `"15GB"`, `"512MB"`, `"4096Mi"`) or raw byte integers. 1000-based suffixes: KB, MB, GB, TB. 1024-based suffixes: Ki/KiB, Mi/MiB, Gi/GiB.
     */
    gpuMemory?: pulumi.Input<string | undefined>;
    /**
     * RAM allocated. Accepts human-readable strings (e.g. `"8GB"`, `"512MB"`, `"4096Mi"`) or raw byte integers. 1000-based suffixes: KB, MB, GB, TB. 1024-based suffixes: Ki/KiB, Mi/MiB, Gi/GiB.
     */
    memory?: pulumi.Input<string | undefined>;
}

export interface WorkloadRuntimeReplacementPolicy {
    /**
     * Duration in minutes to keep the old version during replacement. Maps to WAPI `config.keepOldVersionMinutes`.
     */
    keepOldVersionMinutes?: pulumi.Input<number | undefined>;
    /**
     * Duration in minutes for the warmup phase during replacement. Maps to WAPI `config.warmupDurationMinutes`.
     */
    warmupMinutes?: pulumi.Input<number | undefined>;
}
