// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Inputs
{

    public sealed class ArtifactSourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the local directory containing application source files to upload.
        /// </summary>
        [Input("dir", required: true)]
        public Input<string> Dir { get; set; } = null!;

        /// <summary>
        /// SHA-256 fingerprint of `dir` contents, used to detect changes and skip re-upload when unchanged.
        /// </summary>
        [Input("dirHash")]
        public Input<string>? DirHash { get; set; }

        public ArtifactSourceArgs()
        {
        }
        public static new ArtifactSourceArgs Empty => new ArtifactSourceArgs();
    }
}
