// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Inputs
{

    public sealed class CustomMetricTimestampGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Column name.
        /// </summary>
        [Input("columnName")]
        public Input<string>? ColumnName { get; set; }

        /// <summary>
        /// Format.
        /// </summary>
        [Input("timeFormat")]
        public Input<string>? TimeFormat { get; set; }

        public CustomMetricTimestampGetArgs()
        {
        }
        public static new CustomMetricTimestampGetArgs Empty => new CustomMetricTimestampGetArgs();
    }
}
