// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datarobot.Inputs
{

    public sealed class CustomModelResourceSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The memory in MB for the Custom Model.
        /// </summary>
        [Input("memoryMb")]
        public Input<int>? MemoryMb { get; set; }

        /// <summary>
        /// The network access for the Custom Model.
        /// </summary>
        [Input("networkAccess")]
        public Input<string>? NetworkAccess { get; set; }

        /// <summary>
        /// The replicas for the Custom Model.
        /// </summary>
        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        public CustomModelResourceSettingsGetArgs()
        {
        }
        public static new CustomModelResourceSettingsGetArgs Empty => new CustomModelResourceSettingsGetArgs();
    }
}
