// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DataRobotPulumi.Datarobot.Inputs
{

    public sealed class DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of time steps.
        /// </summary>
        [Input("timeSteps", required: true)]
        public Input<int> TimeSteps { get; set; } = null!;

        /// <summary>
        /// The time unit or ROW if windowsBasisUnit is ROW
        /// </summary>
        [Input("timeUnit", required: true)]
        public Input<string> TimeUnit { get; set; } = null!;

        public DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicityArgs()
        {
        }
        public static new DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicityArgs Empty => new DeploymentRetrainingPolicyTimeSeriesOptionsPeriodicityArgs();
    }
}
