// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data set from file
 */
export class CustomModel extends pulumi.CustomResource {
    /**
     * Get an existing CustomModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomModelState, opts?: pulumi.CustomResourceOptions): CustomModel {
        return new CustomModel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datarobot:index/customModel:CustomModel';

    /**
     * Returns true if the given object is an instance of CustomModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomModel.__pulumiType;
    }

    /**
     * The ID of the base environment for the Custom Model.
     */
    public readonly baseEnvironmentId!: pulumi.Output<string>;
    /**
     * The name of the base environment for the Custom Model.
     */
    public readonly baseEnvironmentName!: pulumi.Output<string | undefined>;
    /**
     * The ID of the base environment version for the Custom Model.
     */
    public readonly baseEnvironmentVersionId!: pulumi.Output<string>;
    /**
     * The description of the Custom Model.
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * The guard configurations for the Custom Model.
     */
    public readonly guardConfigurations!: pulumi.Output<outputs.CustomModelGuardConfiguration[] | undefined>;
    /**
     * The flag indicating if the Custom Model is a proxy model.
     */
    public readonly isProxy!: pulumi.Output<boolean | undefined>;
    /**
     * The list of local file paths used to build the Custom Model.
     */
    public readonly localFiles!: pulumi.Output<string[] | undefined>;
    /**
     * The name of the Custom Model.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The overall moderation configuration for the Custom Model.
     */
    public readonly overallModerationConfiguration!: pulumi.Output<outputs.CustomModelOverallModerationConfiguration | undefined>;
    /**
     * The runtime parameter values for the Custom Model.
     */
    public readonly runtimeParameters!: pulumi.Output<outputs.CustomModelRuntimeParameter[]>;
    /**
     * The ID of the source LLM Blueprint for the Custom Model.
     */
    public readonly sourceLlmBlueprintId!: pulumi.Output<string | undefined>;
    /**
     * The source remote repositories for the Custom Model.
     */
    public readonly sourceRemoteRepositories!: pulumi.Output<outputs.CustomModelSourceRemoteRepository[] | undefined>;
    /**
     * The target of the Custom Model.
     */
    public readonly target!: pulumi.Output<string | undefined>;
    /**
     * The target type of the Custom Model.
     */
    public readonly targetType!: pulumi.Output<string | undefined>;
    /**
     * The ID of the latest Custom Model version.
     */
    public /*out*/ readonly versionId!: pulumi.Output<string>;

    /**
     * Create a CustomModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomModelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomModelArgs | CustomModelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomModelState | undefined;
            resourceInputs["baseEnvironmentId"] = state ? state.baseEnvironmentId : undefined;
            resourceInputs["baseEnvironmentName"] = state ? state.baseEnvironmentName : undefined;
            resourceInputs["baseEnvironmentVersionId"] = state ? state.baseEnvironmentVersionId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["guardConfigurations"] = state ? state.guardConfigurations : undefined;
            resourceInputs["isProxy"] = state ? state.isProxy : undefined;
            resourceInputs["localFiles"] = state ? state.localFiles : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["overallModerationConfiguration"] = state ? state.overallModerationConfiguration : undefined;
            resourceInputs["runtimeParameters"] = state ? state.runtimeParameters : undefined;
            resourceInputs["sourceLlmBlueprintId"] = state ? state.sourceLlmBlueprintId : undefined;
            resourceInputs["sourceRemoteRepositories"] = state ? state.sourceRemoteRepositories : undefined;
            resourceInputs["target"] = state ? state.target : undefined;
            resourceInputs["targetType"] = state ? state.targetType : undefined;
            resourceInputs["versionId"] = state ? state.versionId : undefined;
        } else {
            const args = argsOrState as CustomModelArgs | undefined;
            if ((!args || args.description === undefined) && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["baseEnvironmentId"] = args ? args.baseEnvironmentId : undefined;
            resourceInputs["baseEnvironmentName"] = args ? args.baseEnvironmentName : undefined;
            resourceInputs["baseEnvironmentVersionId"] = args ? args.baseEnvironmentVersionId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["guardConfigurations"] = args ? args.guardConfigurations : undefined;
            resourceInputs["isProxy"] = args ? args.isProxy : undefined;
            resourceInputs["localFiles"] = args ? args.localFiles : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["overallModerationConfiguration"] = args ? args.overallModerationConfiguration : undefined;
            resourceInputs["runtimeParameters"] = args ? args.runtimeParameters : undefined;
            resourceInputs["sourceLlmBlueprintId"] = args ? args.sourceLlmBlueprintId : undefined;
            resourceInputs["sourceRemoteRepositories"] = args ? args.sourceRemoteRepositories : undefined;
            resourceInputs["target"] = args ? args.target : undefined;
            resourceInputs["targetType"] = args ? args.targetType : undefined;
            resourceInputs["versionId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomModel.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomModel resources.
 */
export interface CustomModelState {
    /**
     * The ID of the base environment for the Custom Model.
     */
    baseEnvironmentId?: pulumi.Input<string>;
    /**
     * The name of the base environment for the Custom Model.
     */
    baseEnvironmentName?: pulumi.Input<string>;
    /**
     * The ID of the base environment version for the Custom Model.
     */
    baseEnvironmentVersionId?: pulumi.Input<string>;
    /**
     * The description of the Custom Model.
     */
    description?: pulumi.Input<string>;
    /**
     * The guard configurations for the Custom Model.
     */
    guardConfigurations?: pulumi.Input<pulumi.Input<inputs.CustomModelGuardConfiguration>[]>;
    /**
     * The flag indicating if the Custom Model is a proxy model.
     */
    isProxy?: pulumi.Input<boolean>;
    /**
     * The list of local file paths used to build the Custom Model.
     */
    localFiles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the Custom Model.
     */
    name?: pulumi.Input<string>;
    /**
     * The overall moderation configuration for the Custom Model.
     */
    overallModerationConfiguration?: pulumi.Input<inputs.CustomModelOverallModerationConfiguration>;
    /**
     * The runtime parameter values for the Custom Model.
     */
    runtimeParameters?: pulumi.Input<pulumi.Input<inputs.CustomModelRuntimeParameter>[]>;
    /**
     * The ID of the source LLM Blueprint for the Custom Model.
     */
    sourceLlmBlueprintId?: pulumi.Input<string>;
    /**
     * The source remote repositories for the Custom Model.
     */
    sourceRemoteRepositories?: pulumi.Input<pulumi.Input<inputs.CustomModelSourceRemoteRepository>[]>;
    /**
     * The target of the Custom Model.
     */
    target?: pulumi.Input<string>;
    /**
     * The target type of the Custom Model.
     */
    targetType?: pulumi.Input<string>;
    /**
     * The ID of the latest Custom Model version.
     */
    versionId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CustomModel resource.
 */
export interface CustomModelArgs {
    /**
     * The ID of the base environment for the Custom Model.
     */
    baseEnvironmentId?: pulumi.Input<string>;
    /**
     * The name of the base environment for the Custom Model.
     */
    baseEnvironmentName?: pulumi.Input<string>;
    /**
     * The ID of the base environment version for the Custom Model.
     */
    baseEnvironmentVersionId?: pulumi.Input<string>;
    /**
     * The description of the Custom Model.
     */
    description: pulumi.Input<string>;
    /**
     * The guard configurations for the Custom Model.
     */
    guardConfigurations?: pulumi.Input<pulumi.Input<inputs.CustomModelGuardConfiguration>[]>;
    /**
     * The flag indicating if the Custom Model is a proxy model.
     */
    isProxy?: pulumi.Input<boolean>;
    /**
     * The list of local file paths used to build the Custom Model.
     */
    localFiles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the Custom Model.
     */
    name?: pulumi.Input<string>;
    /**
     * The overall moderation configuration for the Custom Model.
     */
    overallModerationConfiguration?: pulumi.Input<inputs.CustomModelOverallModerationConfiguration>;
    /**
     * The runtime parameter values for the Custom Model.
     */
    runtimeParameters?: pulumi.Input<pulumi.Input<inputs.CustomModelRuntimeParameter>[]>;
    /**
     * The ID of the source LLM Blueprint for the Custom Model.
     */
    sourceLlmBlueprintId?: pulumi.Input<string>;
    /**
     * The source remote repositories for the Custom Model.
     */
    sourceRemoteRepositories?: pulumi.Input<pulumi.Input<inputs.CustomModelSourceRemoteRepository>[]>;
    /**
     * The target of the Custom Model.
     */
    target?: pulumi.Input<string>;
    /**
     * The target type of the Custom Model.
     */
    targetType?: pulumi.Input<string>;
}
