// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Custom Job
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@datarobot/pulumi-datarobot";
 *
 * const example = new datarobot.CustomMetricJob("example", {
 *     name: "Example Custom Metric Job",
 *     files: [
 *         "file1.py",
 *         "file2.py",
 *     ],
 *     environmentId: "65f9b27eab986d30d4c64268",
 *     description: "Example Custom Metric Job Description",
 *     runtimeParameterValues: [{
 *         key: "EXAMPLE_PARAM",
 *         type: "string",
 *         value: "val",
 *     }],
 *     egressNetworkPolicy: "none",
 *     resourceBundleId: "cpu.micro",
 *     units: "count",
 *     directionality: "lowerIsBetter",
 *     type: "sum",
 *     isModelSpecific: false,
 * });
 * export const exampleId = example.id;
 * ```
 * <!--End PulumiCodeChooser -->
 */
export class CustomMetricJob extends pulumi.CustomResource {
    /**
     * Get an existing CustomMetricJob resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomMetricJobState, opts?: pulumi.CustomResourceOptions): CustomMetricJob {
        return new CustomMetricJob(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datarobot:index/customMetricJob:CustomMetricJob';

    /**
     * Returns true if the given object is an instance of CustomMetricJob.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomMetricJob {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomMetricJob.__pulumiType;
    }

    /**
     * The description of the Custom Metric Job.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The directionality of the Custom Metric.
     */
    declare public readonly directionality: pulumi.Output<string>;
    /**
     * The egress network policy for the Job.
     */
    declare public readonly egressNetworkPolicy: pulumi.Output<string>;
    /**
     * The ID of the environment to use with the Job.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * The ID of the environment version to use with the Job.
     */
    declare public readonly environmentVersionId: pulumi.Output<string>;
    /**
     * The list of tuples, where values in each tuple are the local filesystem path and the path the file should be placed in the Job. If list is of strings, then basenames will be used for tuples.
     */
    declare public readonly files: pulumi.Output<any | undefined>;
    /**
     * The hash of file contents for each file in files.
     */
    declare public /*out*/ readonly filesHashes: pulumi.Output<string[]>;
    /**
     * The path to a folder containing files to be uploaded. Each file in the folder is uploaded under path relative to a folder path.
     */
    declare public readonly folderPath: pulumi.Output<string | undefined>;
    /**
     * The hash of the folder path contents.
     */
    declare public /*out*/ readonly folderPathHash: pulumi.Output<string>;
    /**
     * Determines whether the metric is related to the model or deployment.
     */
    declare public readonly isModelSpecific: pulumi.Output<boolean>;
    /**
     * The name of the Custom Metric Job.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc.
     */
    declare public readonly resourceBundleId: pulumi.Output<string | undefined>;
    /**
     * Additional parameters to be injected into a Job at runtime.
     */
    declare public readonly runtimeParameterValues: pulumi.Output<outputs.CustomMetricJobRuntimeParameterValue[]>;
    /**
     * Custom metric time bucket size.
     */
    declare public readonly timeStep: pulumi.Output<string>;
    /**
     * The aggregation type of the custom metric.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * The units, or the y-axis label, of the given custom metric.
     */
    declare public readonly units: pulumi.Output<string>;

    /**
     * Create a CustomMetricJob resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CustomMetricJobArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomMetricJobArgs | CustomMetricJobState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomMetricJobState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["directionality"] = state?.directionality;
            resourceInputs["egressNetworkPolicy"] = state?.egressNetworkPolicy;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["environmentVersionId"] = state?.environmentVersionId;
            resourceInputs["files"] = state?.files;
            resourceInputs["filesHashes"] = state?.filesHashes;
            resourceInputs["folderPath"] = state?.folderPath;
            resourceInputs["folderPathHash"] = state?.folderPathHash;
            resourceInputs["isModelSpecific"] = state?.isModelSpecific;
            resourceInputs["name"] = state?.name;
            resourceInputs["resourceBundleId"] = state?.resourceBundleId;
            resourceInputs["runtimeParameterValues"] = state?.runtimeParameterValues;
            resourceInputs["timeStep"] = state?.timeStep;
            resourceInputs["type"] = state?.type;
            resourceInputs["units"] = state?.units;
        } else {
            const args = argsOrState as CustomMetricJobArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["directionality"] = args?.directionality;
            resourceInputs["egressNetworkPolicy"] = args?.egressNetworkPolicy;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["environmentVersionId"] = args?.environmentVersionId;
            resourceInputs["files"] = args?.files;
            resourceInputs["folderPath"] = args?.folderPath;
            resourceInputs["isModelSpecific"] = args?.isModelSpecific;
            resourceInputs["name"] = args?.name;
            resourceInputs["resourceBundleId"] = args?.resourceBundleId;
            resourceInputs["runtimeParameterValues"] = args?.runtimeParameterValues;
            resourceInputs["timeStep"] = args?.timeStep;
            resourceInputs["type"] = args?.type;
            resourceInputs["units"] = args?.units;
            resourceInputs["filesHashes"] = undefined /*out*/;
            resourceInputs["folderPathHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomMetricJob.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomMetricJob resources.
 */
export interface CustomMetricJobState {
    /**
     * The description of the Custom Metric Job.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The directionality of the Custom Metric.
     */
    directionality?: pulumi.Input<string | undefined>;
    /**
     * The egress network policy for the Job.
     */
    egressNetworkPolicy?: pulumi.Input<string | undefined>;
    /**
     * The ID of the environment to use with the Job.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the environment version to use with the Job.
     */
    environmentVersionId?: pulumi.Input<string | undefined>;
    /**
     * The list of tuples, where values in each tuple are the local filesystem path and the path the file should be placed in the Job. If list is of strings, then basenames will be used for tuples.
     */
    files?: any | undefined;
    /**
     * The hash of file contents for each file in files.
     */
    filesHashes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The path to a folder containing files to be uploaded. Each file in the folder is uploaded under path relative to a folder path.
     */
    folderPath?: pulumi.Input<string | undefined>;
    /**
     * The hash of the folder path contents.
     */
    folderPathHash?: pulumi.Input<string | undefined>;
    /**
     * Determines whether the metric is related to the model or deployment.
     */
    isModelSpecific?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the Custom Metric Job.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc.
     */
    resourceBundleId?: pulumi.Input<string | undefined>;
    /**
     * Additional parameters to be injected into a Job at runtime.
     */
    runtimeParameterValues?: pulumi.Input<pulumi.Input<inputs.CustomMetricJobRuntimeParameterValue>[] | undefined>;
    /**
     * Custom metric time bucket size.
     */
    timeStep?: pulumi.Input<string | undefined>;
    /**
     * The aggregation type of the custom metric.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * The units, or the y-axis label, of the given custom metric.
     */
    units?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a CustomMetricJob resource.
 */
export interface CustomMetricJobArgs {
    /**
     * The description of the Custom Metric Job.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The directionality of the Custom Metric.
     */
    directionality?: pulumi.Input<string | undefined>;
    /**
     * The egress network policy for the Job.
     */
    egressNetworkPolicy?: pulumi.Input<string | undefined>;
    /**
     * The ID of the environment to use with the Job.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the environment version to use with the Job.
     */
    environmentVersionId?: pulumi.Input<string | undefined>;
    /**
     * The list of tuples, where values in each tuple are the local filesystem path and the path the file should be placed in the Job. If list is of strings, then basenames will be used for tuples.
     */
    files?: any | undefined;
    /**
     * The path to a folder containing files to be uploaded. Each file in the folder is uploaded under path relative to a folder path.
     */
    folderPath?: pulumi.Input<string | undefined>;
    /**
     * Determines whether the metric is related to the model or deployment.
     */
    isModelSpecific?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the Custom Metric Job.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A single identifier that represents a bundle of resources: Memory, CPU, GPU, etc.
     */
    resourceBundleId?: pulumi.Input<string | undefined>;
    /**
     * Additional parameters to be injected into a Job at runtime.
     */
    runtimeParameterValues?: pulumi.Input<pulumi.Input<inputs.CustomMetricJobRuntimeParameterValue>[] | undefined>;
    /**
     * Custom metric time bucket size.
     */
    timeStep?: pulumi.Input<string | undefined>;
    /**
     * The aggregation type of the custom metric.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * The units, or the y-axis label, of the given custom metric.
     */
    units?: pulumi.Input<string | undefined>;
}
