// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Data set from file
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@datarobot/pulumi-datarobot";
 *
 * const example = new datarobot.DatasetFromUrl("example", {
 *     url: "[URL to upload from]",
 *     useCaseIds: [exampleDatarobotUseCase.id],
 *     name: "Example Dataset",
 * });
 * export const exampleId = example.id;
 * ```
 * <!--End PulumiCodeChooser -->
 */
export class DatasetFromUrl extends pulumi.CustomResource {
    /**
     * Get an existing DatasetFromUrl resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatasetFromUrlState, opts?: pulumi.CustomResourceOptions): DatasetFromUrl {
        return new DatasetFromUrl(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datarobot:index/datasetFromUrl:DatasetFromUrl';

    /**
     * Returns true if the given object is an instance of DatasetFromUrl.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatasetFromUrl {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatasetFromUrl.__pulumiType;
    }

    /**
     * The name of the Dataset.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The URL to upload the Dataset from.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * The list of Use Case IDs to add the Dataset to.
     */
    declare public readonly useCaseIds: pulumi.Output<string[] | undefined>;

    /**
     * Create a DatasetFromUrl resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatasetFromUrlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatasetFromUrlArgs | DatasetFromUrlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatasetFromUrlState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["url"] = state?.url;
            resourceInputs["useCaseIds"] = state?.useCaseIds;
        } else {
            const args = argsOrState as DatasetFromUrlArgs | undefined;
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["url"] = args?.url;
            resourceInputs["useCaseIds"] = args?.useCaseIds;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatasetFromUrl.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DatasetFromUrl resources.
 */
export interface DatasetFromUrlState {
    /**
     * The name of the Dataset.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The URL to upload the Dataset from.
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * The list of Use Case IDs to add the Dataset to.
     */
    useCaseIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a DatasetFromUrl resource.
 */
export interface DatasetFromUrlArgs {
    /**
     * The name of the Dataset.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The URL to upload the Dataset from.
     */
    url: pulumi.Input<string>;
    /**
     * The list of Use Case IDs to add the Dataset to.
     */
    useCaseIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
