// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * List Workload API artifacts with optional status filter and result limit. Each entry mirrors the full artifact API response, including spec.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@pulumi/datarobot";
 *
 * const all = datarobot.getArtifacts({});
 * export const artifactCount = all.then(all => all.artifacts).length;
 * export const artifactNames = all.then(all => .map(a => (a.name)));
 * ```
 */
export function getArtifacts(args?: GetArtifactsArgs, opts?: pulumi.InvokeOptions): Promise<GetArtifactsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datarobot:index/getArtifacts:getArtifacts", {
        "limit": args.limit,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getArtifacts.
 */
export interface GetArtifactsArgs {
    /**
     * Maximum number of artifacts to return. When omitted, all matching artifacts are returned (paginated in pages of 100).
     */
    limit?: number;
    /**
     * Filter artifacts by status: `draft` or `locked`.
     */
    status?: string;
}

/**
 * A collection of values returned by getArtifacts.
 */
export interface GetArtifactsResult {
    /**
     * Artifacts matching the filter.
     */
    readonly artifacts: outputs.GetArtifactsArtifact[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Maximum number of artifacts to return. When omitted, all matching artifacts are returned (paginated in pages of 100).
     */
    readonly limit?: number;
    /**
     * Filter artifacts by status: `draft` or `locked`.
     */
    readonly status?: string;
}
/**
 * List Workload API artifacts with optional status filter and result limit. Each entry mirrors the full artifact API response, including spec.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@pulumi/datarobot";
 *
 * const all = datarobot.getArtifacts({});
 * export const artifactCount = all.then(all => all.artifacts).length;
 * export const artifactNames = all.then(all => .map(a => (a.name)));
 * ```
 */
export function getArtifactsOutput(args?: GetArtifactsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetArtifactsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datarobot:index/getArtifacts:getArtifacts", {
        "limit": args.limit,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getArtifacts.
 */
export interface GetArtifactsOutputArgs {
    /**
     * Maximum number of artifacts to return. When omitted, all matching artifacts are returned (paginated in pages of 100).
     */
    limit?: pulumi.Input<number>;
    /**
     * Filter artifacts by status: `draft` or `locked`.
     */
    status?: pulumi.Input<string>;
}
