// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Look up an existing Workload API artifact by ID. Returns the full artifact definition including spec, status, creator, tags, and permissions.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@pulumi/datarobot";
 *
 * const existing = datarobot.getArtifact({
 *     artifactId: _var.artifact_id,
 * });
 * export const artifactName = existing.then(existing => existing.name);
 * export const artifactStatus = existing.then(existing => existing.status);
 * ```
 */
export function getArtifact(args: GetArtifactArgs, opts?: pulumi.InvokeOptions): Promise<GetArtifactResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datarobot:index/getArtifact:getArtifact", {
        "artifactId": args.artifactId,
    }, opts);
}

/**
 * A collection of arguments for invoking getArtifact.
 */
export interface GetArtifactArgs {
    /**
     * The artifact version ID to look up.
     */
    artifactId: string;
}

/**
 * A collection of values returned by getArtifact.
 */
export interface GetArtifactResult {
    /**
     * The artifact version ID to look up.
     */
    readonly artifactId: string;
    /**
     * ID of the artifact repository for versioning.
     */
    readonly artifactRepositoryId: string;
    /**
     * Timestamp of when the artifact was created.
     */
    readonly createdAt: string;
    /**
     * User who created the artifact.
     */
    readonly creator: outputs.GetArtifactCreator;
    /**
     * The description of the Artifact.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the Artifact.
     */
    readonly name: string;
    /**
     * Effective repository-level permissions for the authenticated user.
     */
    readonly permissions: string[];
    /**
     * The artifact specification containing container group definitions.
     */
    readonly spec: outputs.GetArtifactSpec;
    /**
     * Artifact status: `draft` or `locked`.
     */
    readonly status: string;
    /**
     * Tags associated with this artifact.
     */
    readonly tags: outputs.GetArtifactTag[];
    /**
     * The artifact type: `service` or `nim`.
     */
    readonly type: string;
    /**
     * Timestamp of when the artifact was last updated.
     */
    readonly updatedAt: string;
    /**
     * Version number of the artifact. Set only for locked artifacts.
     */
    readonly version: number;
}
/**
 * Look up an existing Workload API artifact by ID. Returns the full artifact definition including spec, status, creator, tags, and permissions.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@pulumi/datarobot";
 *
 * const existing = datarobot.getArtifact({
 *     artifactId: _var.artifact_id,
 * });
 * export const artifactName = existing.then(existing => existing.name);
 * export const artifactStatus = existing.then(existing => existing.status);
 * ```
 */
export function getArtifactOutput(args: GetArtifactOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetArtifactResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datarobot:index/getArtifact:getArtifact", {
        "artifactId": args.artifactId,
    }, opts);
}

/**
 * A collection of arguments for invoking getArtifact.
 */
export interface GetArtifactOutputArgs {
    /**
     * The artifact version ID to look up.
     */
    artifactId: pulumi.Input<string>;
}
