// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Looks up a directory group by name and returns its ID, so that group memberships and shares can be expressed by name rather than by hardcoded ID.
 *
 * Names are matched in full and case sensitively, so the name must be given exactly as it appears in the identity provider. Results are scoped to the caller's organization.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@datarobot/pulumi-datarobot";
 *
 * const finance = datarobot.getGroup({
 *     name: "FinanceTeam",
 * });
 * export const financeGroupId = finance.then(finance => finance.id);
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getGroup(args: GetGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datarobot:index/getGroup:getGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getGroup.
 */
export interface GetGroupArgs {
    /**
     * The name of the group, matched in full and case sensitively.
     */
    name: string;
}

/**
 * A collection of values returned by getGroup.
 */
export interface GetGroupResult {
    /**
     * The description of the group, or null if none is set.
     */
    readonly description: string;
    /**
     * The ID of the group.
     */
    readonly id: string;
    /**
     * The name of the group, matched in full and case sensitively.
     */
    readonly name: string;
    /**
     * How the group is provisioned: <span pulumi-lang-nodejs="`scim`" pulumi-lang-dotnet="`Scim`" pulumi-lang-go="`scim`" pulumi-lang-python="`scim`" pulumi-lang-yaml="`scim`" pulumi-lang-java="`scim`" pulumi-lang-hcl="`scim`">`scim`</span> when synced from an external identity provider, <span pulumi-lang-nodejs="`local`" pulumi-lang-dotnet="`Local`" pulumi-lang-go="`local`" pulumi-lang-python="`local`" pulumi-lang-yaml="`local`" pulumi-lang-java="`local`" pulumi-lang-hcl="`local`">`local`</span> when created in DataRobot.
     */
    readonly provisioningSource: string;
}
/**
 * Looks up a directory group by name and returns its ID, so that group memberships and shares can be expressed by name rather than by hardcoded ID.
 *
 * Names are matched in full and case sensitively, so the name must be given exactly as it appears in the identity provider. Results are scoped to the caller's organization.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datarobot from "@datarobot/pulumi-datarobot";
 *
 * const finance = datarobot.getGroup({
 *     name: "FinanceTeam",
 * });
 * export const financeGroupId = finance.then(finance => finance.id);
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getGroupOutput(args: GetGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datarobot:index/getGroup:getGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getGroup.
 */
export interface GetGroupOutputArgs {
    /**
     * The name of the group, matched in full and case sensitively.
     */
    name: pulumi.Input<string>;
}
