// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Api Token Credential
 */
export class GoogleCloudCredential extends pulumi.CustomResource {
    /**
     * Get an existing GoogleCloudCredential resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GoogleCloudCredentialState, opts?: pulumi.CustomResourceOptions): GoogleCloudCredential {
        return new GoogleCloudCredential(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datarobot:index/googleCloudCredential:GoogleCloudCredential';

    /**
     * Returns true if the given object is an instance of GoogleCloudCredential.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GoogleCloudCredential {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GoogleCloudCredential.__pulumiType;
    }

    /**
     * The GCP key in JSON format.
     */
    declare public readonly gcpKey: pulumi.Output<string | undefined>;
    /**
     * The file that has the GCP key. Cannot be used with <span pulumi-lang-nodejs="`gcpKey`" pulumi-lang-dotnet="`GcpKey`" pulumi-lang-go="`gcpKey`" pulumi-lang-python="`gcp_key`" pulumi-lang-yaml="`gcpKey`" pulumi-lang-java="`gcpKey`" pulumi-lang-hcl="`gcp_key`">`gcpKey`</span>.
     */
    declare public readonly gcpKeyFile: pulumi.Output<string | undefined>;
    /**
     * The hash of the GCP key file contents.
     */
    declare public /*out*/ readonly gcpKeyFileHash: pulumi.Output<string>;
    /**
     * The name of the Google Cloud Credential.
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a GoogleCloudCredential resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GoogleCloudCredentialArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GoogleCloudCredentialArgs | GoogleCloudCredentialState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GoogleCloudCredentialState | undefined;
            resourceInputs["gcpKey"] = state?.gcpKey;
            resourceInputs["gcpKeyFile"] = state?.gcpKeyFile;
            resourceInputs["gcpKeyFileHash"] = state?.gcpKeyFileHash;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as GoogleCloudCredentialArgs | undefined;
            resourceInputs["gcpKey"] = args?.gcpKey ? pulumi.secret(args.gcpKey) : undefined;
            resourceInputs["gcpKeyFile"] = args?.gcpKeyFile;
            resourceInputs["name"] = args?.name;
            resourceInputs["gcpKeyFileHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["gcpKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GoogleCloudCredential.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GoogleCloudCredential resources.
 */
export interface GoogleCloudCredentialState {
    /**
     * The GCP key in JSON format.
     */
    gcpKey?: pulumi.Input<string | undefined>;
    /**
     * The file that has the GCP key. Cannot be used with <span pulumi-lang-nodejs="`gcpKey`" pulumi-lang-dotnet="`GcpKey`" pulumi-lang-go="`gcpKey`" pulumi-lang-python="`gcp_key`" pulumi-lang-yaml="`gcpKey`" pulumi-lang-java="`gcpKey`" pulumi-lang-hcl="`gcp_key`">`gcpKey`</span>.
     */
    gcpKeyFile?: pulumi.Input<string | undefined>;
    /**
     * The hash of the GCP key file contents.
     */
    gcpKeyFileHash?: pulumi.Input<string | undefined>;
    /**
     * The name of the Google Cloud Credential.
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a GoogleCloudCredential resource.
 */
export interface GoogleCloudCredentialArgs {
    /**
     * The GCP key in JSON format.
     */
    gcpKey?: pulumi.Input<string | undefined>;
    /**
     * The file that has the GCP key. Cannot be used with <span pulumi-lang-nodejs="`gcpKey`" pulumi-lang-dotnet="`GcpKey`" pulumi-lang-go="`gcpKey`" pulumi-lang-python="`gcp_key`" pulumi-lang-yaml="`gcpKey`" pulumi-lang-java="`gcpKey`" pulumi-lang-hcl="`gcp_key`">`gcpKey`</span>.
     */
    gcpKeyFile?: pulumi.Input<string | undefined>;
    /**
     * The name of the Google Cloud Credential.
     */
    name?: pulumi.Input<string | undefined>;
}
